### PR TITLE
Take into account DependencyKind when collecting package target dependencies

### LINKED ISSUE #2059: Build / Optional Dependency Regression in v0.25.1
We currently updated from rules `v0.19` to `v0.25` so we could get the conditional compilation of dependencies based off the architecture platform to work.  While doing that, we noticed that optional dependencies in downstream crates broke.  

I have a small hello world reproduction of this behavior here (We have seen this in the parking_lot crate, and the cucumber crate).  

https://github.com/ericmcbride/bazel-deps-broke

### Steps to Reproduce
1.) In `WORKSPACE.bazel` we have `v0.19` have by default.  If you run `bazel run //test_crate:example` it should compile and will complain about a missing feature file path.     
2.) In `WORKSPACE.bazel` if you change rules rust to the commented out  `urls: v0.25.1` and the coordinated `sha256`, run `CARGO_BAZEL_REPIN=1 bazel sync --only=crate_index`   
3.) `bazel clean --expunge` to bust the local sandbox cache  
4.) then rerun the `bazel run //test_crate::example` command and you will see the following error:  

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error[E0433]: failed to resolve: use of undeclared crate or module `serde`
 --> external/bazel_deps__gherkin-0.13.0/build.rs:6:17
  |
6 | #[derive(Debug, serde::Deserialize)]
  |                 ^^^^^ use of undeclared crate or module `serde`

error: cannot find attribute `serde` in this scope
 --> external/bazel_deps__gherkin-0.13.0/build.rs:7:3
  |
7 | #[serde(rename_all = "camelCase")]
  |   ^^^^^

error[E0277]: the trait bound `Data: serde::de::Deserialize<'_>` is not satisfied
  --> external/bazel_deps__gherkin-0.13.0/build.rs:31:41
   |
31 |     let langs: BTreeMap<String, Data> = serde_json::from_str(&f).unwrap();
   |                                         ^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `Data`
   |
   = help: the following other types implement trait `serde::de::Deserialize<'de>`:
             &'a [u8]
             &'a std::path::Path
             &'a str
             ()
             (T0, T1)
             (T0, T1, T2)
             (T0, T1, T2, T3)
             (T0, T1, T2, T3, T4)
           and 129 others
   = note: required for `BTreeMap<std::string::String, Data>` to implement `serde::de::Deserialize<'_>`
note: required by a bound in `serde_json::from_str`
  --> external/bazel_deps__serde_json-1.0.100/src/de.rs:2603:8
   |
   = note: required by this bound in `serde_json::from_str`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0277, E0433.
For more information about an error, try `rustc --explain E0277`.

```

We have also witnessed this behavior with feature flag gated dependencies, in our case, `parking_lot`

While running cargo, everything compiles and works fine.

### PR DESCRIPTION
**Pull request by dmitrii-ubskii**
When filtering out disabled dependencies for the Bazel targets, `collect_deps_selectable()` now takes into account the kind of dependency in question. Previously, if a disabled optional normal dependency was mandatory for a build script, it was erroneously filtered out.

This change resolves #2059

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]
Thanks! All that's needed is a rebase and this can then be merged 😄

**Comment by dmitrii-ubskii** [comment]
Rebased!

**Comment by UebelAndre** [comment]
Alas! I’m too late and another change was merged lol. One more rebase?

**Comment by dmitrii-ubskii** [comment]
Done.

**Pull request merged**
