### PR TITLE
Release 0.55.1

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]
Happy to try! Or to wait!

**Review by illicitonion — COMMENTED** [review]
Wait... Do we need to bump the versions in the other extensions too?

I see extensions/prost/MODULE.bazel still as 0.54.1 (and depending on rules_rust 0.54.1)...

**Comment by UebelAndre** [comment]
> Wait... Do we need to bump the versions in the other extensions too?
> 
> I see extensions/prost/MODULE.bazel still as 0.54.1 (and depending on rules_rust 0.54.1)...

Great catch! I created https://github.com/bazelbuild/rules_rust/pull/3052 to prevent this in the future

**Comment by UebelAndre** [comment]
I think https://github.com/bazelbuild/rules_rust/pull/3053 suggests that we should cut this release.

**Pull request merged**
