### PR TITLE
Add Fuchsia platform support

### PR DESCRIPTION
**Pull request by P1n3appl3**
This is needed because crates_universe spits out selects for target specific deps (like `target.'cfg(unix)'.dependencies`).

I tried to go about this by adding `<arch>-unknown-fuchsia` to the `SUPPORTED_T2_PLATFORM_TRIPLES` list in `rust/platform/triple_mappings.bzl`, but unfortunately the `cfg-expr` crate that crates_universe uses hasn't been updated yet and is only aware of the older `<arch>-fuchsia` triples so it emits those. It seems that any non-3-component triples need to be special cased like this. Once they update (probably around when 1.68 releases) I can remove these and add it to that list.

### CODE REVIEW

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Why not add another exception to `triple.bzl`?

https://github.com/bazelbuild/rules_rust/blob/0.18.0/rust/platform/triple.bzl#L24-L31

**Comment by UebelAndre** [comment]
@P1n3appl3 friendly ping 😄

**Comment by P1n3appl3** [comment]
Sorry about that, was sick and missed this. Good idea, I've added the logic to `triple.bzl` so fuchsia can go in `triple_mappings.bzl` with the rest of the triples.

**Review by UebelAndre — APPROVED** [review]
Thanks!

**Comment by P1n3appl3** [comment]
Hmm not sure what I'm doing wrong: I tried running a build (and a clean build for good measure) with `REPIN` but the build passes and there's no changed files. I also tried `CARGO_BAZEL_REPIN` which is what shows up in the error from the CI logs but there were still no changes. I can also run the same command that's failing in CI locally (`bazel --nosystem_rc --nohome_rc info`) and it passes for me.

**Comment by UebelAndre** [comment]
@P1n3appl3 are you running in `./examples/crate_universe`? I'm able to do so with these changes and produce the following diff. I suspect if you apply them to your PR you'll get passing builds. That said, this experience far from ideal and for that I apologize but thank you for being willing to work through the PR.

```diff
diff --git a/examples/crate_universe/cargo_aliases/cargo-bazel-lock.json b/examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
index 36918d25..46469d97 100644
--- a/examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
+++ b/examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
@@ -1,5 +1,5 @@
 {
-  "checksum": "c49d1b9f45313c229afa999a17e4f512ba1bb7d498dbb963261110ec84029640",
+  "checksum": "0b8bcc788436e0cce24114965b6d1392083684bf072490de4a8ac33065fc5d48",
   "crates": {
     "aho-corasick 0.7.20": {
       "name": "aho-corasick",
@@ -2430,6 +2430,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -2443,6 +2444,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
diff --git a/examples/crate_universe/cargo_workspace/cargo-bazel-lock.json b/examples/crate_universe/cargo_workspace/cargo-bazel-lock.json
index bed2b838..abb6e150 100644
--- a/examples/crate_universe/cargo_workspace/cargo-bazel-lock.json
+++ b/examples/crate_universe/cargo_workspace/cargo-bazel-lock.json
@@ -1,5 +1,5 @@
 {
-  "checksum": "135c580c72860ef56a1f170c92e1552f0b4fa6efb8b94a9da71cba230e3a5f5e",
+  "checksum": "75fdcd264c7e16df76a07dc5497df29e4c779646a0b1e64ba3322c1b1dd38235",
   "crates": {
     "ansi_term 0.12.1": {
       "name": "ansi_term",
@@ -1279,6 +1279,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -1298,6 +1299,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -1307,6 +1309,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -1324,6 +1327,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
@@ -1342,6 +1346,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -1355,6 +1360,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
diff --git a/examples/crate_universe/multi_package/cargo-bazel-lock.json b/examples/crate_universe/multi_package/cargo-bazel-lock.json
index 772fb3c1..33c20aa8 100644
--- a/examples/crate_universe/multi_package/cargo-bazel-lock.json
+++ b/examples/crate_universe/multi_package/cargo-bazel-lock.json
@@ -1,5 +1,5 @@
 {
-  "checksum": "ce89c23b74e04f3901c0d8c3809a9c71c7f12e81cff3bff597221fb81ace4883",
+  "checksum": "d16c9317f1243b555c71f8861dff9cb32aa8904991bab84fc49dd1fc6d3c94c6",
   "crates": {
     "aho-corasick 0.7.20": {
       "name": "aho-corasick",
@@ -9331,6 +9331,7 @@
       "wasm32-unknown-unknown"
     ],
     "cfg(any(target_arch = \"x86\", target_arch = \"x86_64\", all(any(target_arch = \"aarch64\", target_arch = \"arm\"), any(target_os = \"android\", target_os = \"fuchsia\", target_os = \"linux\"))))": [
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -9343,6 +9344,7 @@
       "i686-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -9369,6 +9371,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -9382,6 +9385,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
@@ -9391,6 +9395,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -9408,6 +9413,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -9417,6 +9423,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -9434,6 +9441,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -9443,6 +9451,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -9461,6 +9470,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -9470,6 +9480,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -9487,6 +9498,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
@@ -9495,6 +9507,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -9514,6 +9527,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -9541,6 +9555,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -9554,6 +9569,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
diff --git a/examples/crate_universe/no_cargo_manifests/cargo-bazel-lock.json b/examples/crate_universe/no_cargo_manifests/cargo-bazel-lock.json
index 1a853a08..dbf8b343 100644
--- a/examples/crate_universe/no_cargo_manifests/cargo-bazel-lock.json
+++ b/examples/crate_universe/no_cargo_manifests/cargo-bazel-lock.json
@@ -1,5 +1,5 @@
 {
-  "checksum": "a57f0fbcc1df33300a48699cf8b802eaa7aa0aac64950a3846811c842098d79c",
+  "checksum": "fce5a79b67115df9717f8f75bca822de3fc5d2ff6a2504a67c34f87d1564a678",
   "crates": {
     "async-trait 0.1.64": {
       "name": "async-trait",
@@ -4868,6 +4868,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -4885,6 +4886,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -4894,6 +4896,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -4911,6 +4914,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
@@ -4919,6 +4923,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-pc-windows-msvc",
       "aarch64-unknown-linux-gnu",
@@ -4938,6 +4943,7 @@
       "wasm32-wasi",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-pc-windows-msvc",
       "x86_64-unknown-freebsd",
@@ -4957,6 +4963,7 @@
       "aarch64-apple-darwin",
       "aarch64-apple-ios",
       "aarch64-apple-ios-sim",
+      "aarch64-fuchsia",
       "aarch64-linux-android",
       "aarch64-unknown-linux-gnu",
       "arm-unknown-linux-gnueabi",
@@ -4970,6 +4977,7 @@
       "s390x-unknown-linux-gnu",
       "x86_64-apple-darwin",
       "x86_64-apple-ios",
+      "x86_64-fuchsia",
       "x86_64-linux-android",
       "x86_64-unknown-freebsd",
       "x86_64-unknown-linux-gnu"
diff --git a/rust/platform/triple.bzl b/rust/platform/triple.bzl
index 6460e2f8..a9638cb1 100644
--- a/rust/platform/triple.bzl
+++ b/rust/platform/triple.bzl
@@ -29,6 +29,14 @@ def triple(triple):
             abi = None,
             str = triple,
         )
+    elif triple in ("aarch64-fuchsia", "x86_64-fuchsia"):
+        return struct(
+            arch = triple.split("-")[0],
+            system = "fuchsia",
+            vendor = "fuchsia",
+            abi = None,
+            str = triple,
+        )
 
     component_parts = triple.split("-")
     if len(component_parts) < 3:
diff --git a/rust/platform/triple_mappings.bzl b/rust/platform/triple_mappings.bzl
index f5b0acf0..e3d2bebc 100644
--- a/rust/platform/triple_mappings.bzl
+++ b/rust/platform/triple_mappings.bzl
@@ -24,6 +24,7 @@ SUPPORTED_T2_PLATFORM_TRIPLES = [
     "aarch64-apple-darwin",
     "aarch64-apple-ios-sim",
     "aarch64-apple-ios",
+    "aarch64-fuchsia",
     "aarch64-linux-android",
     "aarch64-pc-windows-msvc",
     "arm-unknown-linux-gnueabi",
@@ -38,6 +39,7 @@ SUPPORTED_T2_PLATFORM_TRIPLES = [
     "wasm32-unknown-unknown",
     "wasm32-wasi",
     "x86_64-apple-ios",
+    "x86_64-fuchsia",
     "x86_64-linux-android",
     "x86_64-unknown-freebsd",
 ]
@@ -81,6 +83,7 @@ _SYSTEM_TO_BUILTIN_SYS_SUFFIX = {
     "eabi": "none",
     "emscripten": None,
     "freebsd": "freebsd",
+    "fuchsia": "fuchsia",
     "ios": "ios",
     "linux": "linux",
     "nacl": None,
@@ -99,6 +102,7 @@ _SYSTEM_TO_BINARY_EXT = {
     "eabi": "",
     "emscripten": ".js",
     "freebsd": "",
+    "fuchsia": "",
     "ios": "",
     "linux": "",
     "none": "",
@@ -116,6 +120,7 @@ _SYSTEM_TO_STATICLIB_EXT = {
     "eabi": ".a",
     "emscripten": ".js",
     "freebsd": ".a",
+    "fuchsia": ".a",
     "ios": ".a",
     "linux": ".a",
     "none": ".a",
@@ -130,6 +135,7 @@ _SYSTEM_TO_DYLIB_EXT = {
     "eabi": ".so",
     "emscripten": ".js",
     "freebsd": ".so",
+    "fuchsia": ".so",
     "ios": ".dylib",
     "linux": ".so",
     "none": ".so",

```

**Comment by P1n3appl3** [comment]
:facepalm: my bad, i was in `crate_universe/` instead of `examples/crate_universe/`, now it's working fine.

**Comment by UebelAndre** [comment]
Can you rebase and run the same process again to resolve the conflict?

**Pull request merged**
