### PR TITLE
Update bindgen rules to build clang from source.

### PR DESCRIPTION
**Pull request by UebelAndre**
This change updates the default `rust_bindgen` rules to build `libclang` and `clang` from source using the [Bazel rules sourced in the llvm-project repository](https://github.com/llvm/llvm-project/blob/llvmorg-14.0.6/utils/bazel/README.md) for use in `RustBindgen` actions. The version of Clang that Bindgen uses by default is updated `14.0.6` which was what I was able to get building.

Some breaking changes include:
- Users must now load one extra bzl file if they don't already have have `llvm-project` defined in their WORKSPACE.
```
load("@rules_rust//bindgen:transitive_repositories.bzl", "rust_bindgen_transitive_dependencies")

rust_bindgen_transitive_dependencies()
```
- `rust_bindgen_repositories` is deleted as a means of forcing users to take a look at the updated dependencies.

closes https://github.com/bazelbuild/rules_rust/issues/919

### CODE REVIEW

**Comment by 8573** [comment]
Is there an option not to build Clang from source, for users who don't need that?

**Comment by UebelAndre** [comment]
You should still be able to register your own toolchains

**Comment by UebelAndre** [comment]
Is there an issue you’re running into building clang from source?

**Comment by aaronmondal** [comment]
@UebelAndre Cool change! I want to integrate bindgen-similar functionality between `rules_ll` and `rules_rust` via the `cxx` crate and with this change I can test interop with our bzlmod variant for LLVM.

For reference, LLVM/bzlmod in rules_ll looks like this: https://github.com/eomii/rules_ll/blob/bdd243466d7c5e8be8a9d7f7fcb179b2a1ae084b/MODULE.bazel#L25-L50.

The upstream patch is at https://reviews.llvm.org/D137008. I'll double-check that things are compatible with the usage in `rules_rust` when I find time to revise that patch.

**Pull request merged**
