### PR TITLE
Moved legacy protobuf rules to `proto/protobuf`

### PR DESCRIPTION
**Pull request by UebelAndre**
This aligns better with the `//proto` package now having multiple kinds of rules.

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]
Any thoughts on whether we should rename and/or merge the repository rules for setting up the legacy and the prost/tonic toolchains?

Right now I think they have pretty similar names, and the difference isn't super clear?

**Comment by illicitonion** [comment]
> > Any thoughts on whether we should rename and/or merge the repository rules for setting up the legacy and the prost/tonic toolchains?
> > Right now I think they have pretty similar names, and the difference isn't super clear?
> 
> I was thinking there should be no root level macros anymore to disambiguate the two. What do you think?

Sounds reasonable - I'd be tempted to `s/rust_proto_dependencies/rust_proto_protobuf_dependencies/` or something similar to make the call sites slightly more clear, but I don't really mind :)

**Comment by UebelAndre** [comment]
> Sounds reasonable - I'd be tempted to `s/rust_proto_dependencies/rust_proto_protobuf_dependencies/` or something similar to make the call sites slightly more clear, but I don't really mind :)

Would you do the same for `prost`?
`rust_proto_prost_dependencies` and `rust_proto_protobuf_dependencies`?

**Comment by illicitonion** [comment]
> > Sounds reasonable - I'd be tempted to `s/rust_proto_dependencies/rust_proto_protobuf_dependencies/` or something similar to make the call sites slightly more clear, but I don't really mind :)
> 
> Would you do the same for `prost`? `rust_proto_prost_dependencies` and `rust_proto_protobuf_dependencies`?

Honestly happy either way. I lean towards no because we want it to be the only way in the future, but I would be ok with yes because it's not the only way today.

**Pull request merged**
