### PR TITLE
Add separate proc_macro_deps attr

### PR DESCRIPTION
**Pull request by illicitonion**
Which is always configured in the exec config

Fixes https://github.com/bazelbuild/rules_rust/issues/327
See also https://github.com/google/cargo-raze/pull/164

### CODE REVIEW

**Comment by damienmg** [comment]
/cc @dfreese @smklein 
This change looks good, if the API is fine with the user of it, I would be for moving forward with it.

**Comment by dfreese** [comment]
A little concerned about this from a usability perspective, since the providers for both dep attributes are CrateInfo.  Is there a way to reject the incorrect input on either through an aspect, returning different providers, or perhaps something else?

**Comment by illicitonion** [comment]
> A little concerned about this from a usability perspective, since the providers for both dep attributes are CrateInfo. Is there a way to reject the incorrect input on either through an aspect, returning different providers, or perhaps something else?

Good shout - I've added this check, and also fixed up the problems in the examples repo which it found!

**Comment by damienmg** [comment]
Ok I think that's a go so merging :)

**Comment by djmarcin** [comment]
I suspect this PR may be related to #502 where all proc-macro deps become unconditionally compiled in `opt` which breaks crates that detect the presence of `debug_assertions` internally to do different things (e.g. RustEmbed).

**Pull request merged**
