### PR TITLE
Add CI config to test on RBE.

### PR DESCRIPTION
**Pull request by xingao267**

### CODE REVIEW

**Comment by acmcarther** [comment]
For the record: RBE = "Remote Build Execution"

Change looks good to me % failing build

https://buildkite.com/bazel/rules-rust-rustlang/builds/146#0e40cc59-e453-42d4-ba10-bbb428f9a46d
I can't tell from the failures if this is a rules_rust issue, or an issue with RBE itself. If this is an issue for rules_rust, I can help you work it out.

**Comment by xingao267** [comment]
It looks like all these tests are failing with "error: failed to find a `codegen-backends` folder in the sysroot candidates:".

Internally, we previously test with rules_rust@commit:ef77316503f1ad88c348d9cbc03bf60dbad49317, and these targets are passing fine on RBE:

-- @examples//... -@examples//hello_runfiles:hello_runfiles_test

It seems that there is some regression between ef77316503f1ad88c348d9cbc03bf60dbad49317 and head, that causes more tests broken on RBE.

**Comment by xingao267** [comment]
I've skipped the failing tests in the CI setup, and opened issue https://github.com/bazelbuild/rules_rust/issues/112. We can still setup RBE tests with whatever tests that are currently passing now.

**Comment by acmcarther** [comment]
My bad, I missed this in my toolchain repository refactoring. 

I've got a prospective fix here https://github.com/bazelbuild/rules_rust/compare/acm-fix-remote-exec, now waiting on results from CI.

PR here LGTM.

**Pull request merged**
