### PR TITLE
Updated `rules_nodejs` for wasm_bindgen rules

### PR DESCRIPTION
**Pull request by UebelAndre**
[rules_nodejs](https://github.com/bazelbuild/rules_nodejs) made some updates to the names of some symbols. This PR picks those up so `rules_rust` may also benefit.

### CODE REVIEW

**Comment by UebelAndre** [comment]
This PR is waiting on the actual release of `rules_nodejs` `4.0.0`

**Comment by UebelAndre** [comment]
Also, it seems `rules_nodejs` no longer supports Bazel version `4.0.0` so until `rules_rust` upgrades it's min version, the latest release of `rules_nodejs` will not be usable by the `rust_wasm_bindgen` rule...

**Comment by UebelAndre** [comment]
Actually, rebasing on top of https://github.com/bazelbuild/rules_rust/pull/865 works since in that PR, the `rules_nodejs` repositories are not used when testing the Bazel min version (which is only done on the core rules and tests, not examples).

**Comment by UebelAndre** [comment]
With [rules_nodejs 4.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/4.0.0) out now, this PR can be merged.

**Review by illicitonion — APPROVED** [review]

**Pull request merged**
