### PR TITLE
Added Rust 1.81.0

### PR DESCRIPTION
**Pull request by UebelAndre**
https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html

### CODE REVIEW

**Comment by UebelAndre** [comment]
This change is blocked by https://github.com/bazelbuild/rules_rust/pull/2840

**Review by illicitonion — APPROVED** [review]
LGTM, but I'd ideally like to merge https://github.com/bazelbuild/rules_rust/pull/2851 and hopefully stop disabling the musl job if possible :)

**Comment by UebelAndre** [comment]
@illicitonion looks like the build is still failing 😞

**Comment by illicitonion** [comment]
> @illicitonion looks like the build is still failing 😞
> 
> https://buildkite.com/bazel/rules-rust-rustlang/builds/12063#0191dd06-b0aa-47cc-a03e-73dd0ce45748

I started looking - it looks like on macOS we're using 1.81.0 and on linux we're using 1.80.0... Which seems weird...

**Comment by illicitonion** [comment]
I think the commit I just pushed should fix it :)

**Comment by UebelAndre** [comment]
> I think the commit I just pushed should fix it :)

Seems like it! Sweet but super weird too!

**Pull request merged**
