### PR TITLE
Release 0.41.0

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Comment by UebelAndre** [comment]
I would like the following to be included in this release:
- https://github.com/bazelbuild/rules_rust/pull/2568

**Comment by dzbarsky** [comment]
Can we get https://github.com/bazelbuild/rules_rust/pull/2565 in the release?

**Comment by QuentinPerez** [comment]
what about this one too pls https://github.com/bazelbuild/rules_rust/pull/2545 ?

**Comment by UebelAndre** [comment]
@daivinhtran do you have time for a quick review here?

**Comment by DavidZbarsky-at** [comment]
@UebelAndre should we take https://github.com/bazelbuild/rules_rust/pull/2513 as well since 0.41.0 can finally benefit from it/match cargo semantics?

**Review by scentini — APPROVED** [review]

**Pull request merged**
