### PR TITLE
Update rules_cc to 0.0.9

### PR DESCRIPTION
**Pull request by toandaominh1997**
Update rules_cc to 0.0.9 which has not been upgraded for a long time

### CODE REVIEW

**Comment by toandaominh1997** [comment]
I have upgraded rules_cc from 0.0.1 to 0.0.9 Please help me review these pull requests

**Review by UebelAndre — APPROVED** [review]
Thanks!

**Comment by UebelAndre** [comment]
@toandaominh1997 i think a rebase is required

**Comment by toandaominh1997** [comment]
> @toandaominh1997 i think a rebase is required

I rebase it. Please help me merge this request @UebelAndre

**Pull request merged**
