### PR TITLE
BUG-FIX: host-triple str for bzl mod

### PR DESCRIPTION
**Pull request by ericmcbride**
- Resolves https://github.com/bazelbuild/rules_rust/issues/2585
- Fixes the host triple string lookup for CARGO_BAZEL_URLs. 
- Will work on bzlmod bootstrap so we can bootstrap the bzlmod cargo stuff so we have the URLS in a follow up MR

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]
Thank you!

**Comment by ericmcbride** [comment]
> Thank you!

Looks like the Android CI jobs aren't working for a couple PRs right now

**Comment by UebelAndre** [comment]
> Looks like the Android CI jobs aren't working for a couple PRs right now

I filed https://github.com/bazelbuild/rules_rust/issues/2588

**Comment by cameron-martin** [comment]
Looks like the BCR presubmit is failing due to this same issue: https://github.com/bazelbuild/bazel-central-registry/pull/1704

**Pull request merged**
