### PR TITLE
rustc: fix a conditional

### PR DESCRIPTION
**Pull request by gburgessiv**
`("bar" or "baz")` always evaluates to "bar", so this conditional ignores `"dylib"`. This seems unintended.

I don't have a particular test-case in mind for this; just noticed the oddity as I was browsing through the code.

cc @krasimirgg, who seems to have tweaked things around here recentlyish?

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]
This looks good to me but would now be a change in behavior. @hlopko @scentini I'm wondering what your thoughts are here too.

**Comment by scentini** [comment]
IIUC we currently don't have a use case for `dylib`, so this fix comes at the right time. Thanks!

**Comment by scentini** [comment]
IIUC we currently don't have a use case for `dylib`, so this fix comes at the right time. Thanks!

**Review by scentini — APPROVED** [review]

**Comment by gburgessiv** [comment]
(Thank you all! :) )

**Pull request merged**
