### PR TITLE
rustdoc_test: Apply prefix stripping to proc_macro dependencies.

### PR DESCRIPTION
**Pull request by konkers**
Without stripping the prefix, rustdoc can not find the proc macro shared library.

It's not entirely clear to me why `//test/unit/rustdoc:lib_with_proc_macro` passes without this. When I run `bazel test //test/unit/rustdoc:rustdoc_test_suite     --subcommands` I don't see any "action 'Generating Rustdoc test runner for.." lines so perhaps that path is not tested?

### CODE REVIEW

**Comment by konkers** [comment]
Thanks for the look.   I created an stripped down example repo to illustrate the failure: https://github.com/bazelbuild/rules_rust/pull/1952

**Comment by konkers** [comment]
I noticed in #1782 an additional change is also added:

```rust
        root = proc_macro_dep.crate_info.output.root.path
        if not root in roots:
            roots.append(root)
```

Perhaps that should be added to this PR.

**Comment by armandomontanez** [comment]
I spun up a test that covers this at https://github.com/konkers/rules_rust/pull/1

**Comment by konkers** [comment]
> I spun up a test that covers this at [konkers#1](https://github.com/konkers/rules_rust/pull/1)

Merged into PR

**Comment by armandomontanez** [comment]
@UebelAndre this is ready for another look

**Review by UebelAndre — APPROVED** [review]
Thank you!

**Pull request merged**
