### PR TITLE
Release 0.36.1

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Comment by UebelAndre** [comment]
Record release week! 😄

**Comment by UebelAndre** [comment]
Should include https://github.com/bazelbuild/rules_rust/pull/2375

**Review by illicitonion — APPROVED** [review]
Let's wait on https://github.com/bazelbuild/rules_rust/pull/2372 :)

**Comment by dtolnay** [comment]
Something went wrong with the merge order; https://github.com/bazelbuild/rules_rust/archive/refs/tags/0.36.1.tar.gz includes the changes from #2372 but https://github.com/bazelbuild/rules_rust/releases/download/0.36.1/rules_rust-v0.36.1.tar.gz does not.

**Comment by UebelAndre** [comment]
> Something went wrong with the merge order; https://github.com/bazelbuild/rules_rust/archive/refs/tags/0.36.1.tar.gz includes the changes from #2372 but https://github.com/bazelbuild/rules_rust/releases/download/0.36.1/rules_rust-v0.36.1.tar.gz does not.

Good catch! Filed https://github.com/bazelbuild/rules_rust/issues/2377

**Pull request merged**
