### PR TITLE
Set the Rust target platform triplet using the toolchain description

### PR DESCRIPTION
**Pull request by damienmg**
This change add a 'triplet' information to the toolchain that is
then used to specify the target platform to Rust.

### CODE REVIEW

**Comment by acmcarther** [comment]
This LGTM with a note:

At some later stage, we're going to also want to convert that triple into a fully specified set of flags and vars to make them available for final dependency resolution. This is a stage possibly separate from locking, as described in https://github.com/bazelbuild/rules_rust/pull/100

An example of these details:
https://github.com/acmcarther/cargo-raze-examples/blob/8dba8be7d0ef1e71a4258a5d43c6808f884a7c7f/bazel/complicated_cargo_library/Cargo.bzl#L10-L71

This list was generated via shelling out to `rustc --print=cfg --target=$TARGET` and could be invoked in any manner. It shouldn't change based on the environment it is run under:
https://github.com/acmcarther/cargo-raze/blob/1a2759645ba1e69a230695d1f5d0527a9453789d/src/util.rs#L41-L50

Those details are what are required to fully resolve optional dependencies and flags.

**Comment by damienmg** [comment]
@acmcarther sorry I do not follow, do you mean you want to download the dependency based on the target? The list of config in rustc is set by rustc directly and derived from the target triplet.

**Comment by damienmg** [comment]
Was there any follow-up to be taken here?

**Comment by acmcarther** [comment]
Sorry for the delay.

I don't have any follow up, except to ask that this PR not be submitted. I have a more specific PR that has to break this down by `exec` and `target` which should be ready in a couple of days:

https://github.com/bazelbuild/rules_rust/compare/acm-proper-platform-support#diff-90a5d7c3813ba42b7fcb679e5bb86085R293

**Pull request closed without merging**
