### PR TITLE
Updated CI structure to increase coverage

### PR DESCRIPTION
**Pull request by UebelAndre**
This change is related to https://github.com/bazelbuild/rules_rust/issues/830

### CODE REVIEW

**Comment by UebelAndre** [comment]
This draft contains changes from the following PRs:
- https://github.com/bazelbuild/rules_rust/pull/868
- https://github.com/bazelbuild/rules_rust/pull/869

**Review by illicitonion — APPROVED** [review]
This looks reasonable to me - I'd be tempted (though it's a big step) to maybe write a tiny python script to generate these, rather than writing them all manually, given at this stage we're building up a bit of a combinatorial explosion...

**Comment by UebelAndre** [comment]
> This looks reasonable to me - I'd be tempted (though it's a big step) to maybe write a tiny python script to generate these, rather than writing them all manually, given at this stage we're building up a bit of a combinatorial explosion...

Yeah, but I don't feel like the jobs change so frequently that it's worth that kind of effort. If the issue is that the yaml is not that clear anymore, I'd ask for some pointers in yaml-fu before trying to write some generation tool 😄. Do you have any suggestions on that front?

**Comment by illicitonion** [comment]
> > This looks reasonable to me - I'd be tempted (though it's a big step) to maybe write a tiny python script to generate these, rather than writing them all manually, given at this stage we're building up a bit of a combinatorial explosion...
> 
> Yeah, but I don't feel like the jobs change so frequently that it's worth that kind of effort.

Fair! Now definitely doesn't have to be The Time.

> If the issue is that the yaml is not that clear anymore, I'd ask for some pointers in yaml-fu before trying to write some generation tool 😄. Do you have any suggestions on that front?

In my experience, it's simply not possible to make yaml more readable :)

**Comment by UebelAndre** [comment]
@hlopko If there are no objections from you, I'd like to get this merged. I feel in general it's a good improvement

**Comment by hlopko** [comment]
I stand aside, feel free to merge :)

**Pull request merged**
