### PR TITLE
Make rust_proto_library work with proto_library rules using import_prefix / strip_import_prefix .

### PR DESCRIPTION
**Pull request by lberki**
In addition, this makes it possible to fix http://github.com/bazelbuild/bazel/issues/7157 (patch upcoming)

### CODE REVIEW

**Comment by damienmg** [comment]
This looks correct, but I don't understand from where "_virtual_imports/" is coming? Who generate this?

**Comment by lberki** [comment]
Wow, that was quick :)

Bazel generates this. At HEAD, when the `proto_library` rule uses the `strip_import_prefix` or the `import_prefix` attribute and I want to make it so that it is also generated when the `proto_library` has a generated source (I added you to the internal change).

The code is here:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCommon.java#L294

**Comment by lberki** [comment]
Done. I'll merge then.

**Pull request merged**
