### PR TITLE
Add support for QNX

### PR DESCRIPTION
**Pull request by jondo2010**
This adds the minimum for using `rules_rust` with a self-compiled (tier3) Rust toolchain.

### CODE REVIEW

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Thanks! But I think you'll first need to add the platform to https://github.com/bazelbuild/platforms

**Comment by jondo2010** [comment]
> Thanks! But I think you'll first need to add the platform to https://github.com/bazelbuild/platforms

So `qnx` is already here: https://github.com/bazelbuild/platforms/blob/main/os/BUILD#L97C14-L97C14

**Comment by jondo2010** [comment]
@UebelAndre this should be ready for final review.

**Review by UebelAndre — APPROVED** [review]
Looks good to me, thanks!

**Comment by UebelAndre** [comment]
Just needs a rebase

**Comment by mjpauly** [comment]
This breaks crates_repository for Rust versions <1.67, which is when the \*-nto-qnx\* triples were [introduced](https://releases.rs/docs/1.67.0/). Searchable error:

```
ERROR: An error occurred during the fetch of repository 'crate_index':
   Traceback (most recent call last):
        File "/x/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
                metadata_path = splice_workspace_manifest(
        File "/x/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 178, column 12, in splice_workspace_manifest
                execute(
        File "/x/external/rules_rust/crate_universe/private/common_utils.bzl", line 54, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/x/external/crate_index/cargo-bazel, "splice", "--output-dir", /x/external/crate_index/splicing-output, "--splicing-manifest", /x/external/crate_index/splicing_manifest.json, "--config", /x/external/crate_index/cargo-bazel.json, "--cargo", /x/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/cargo, "--rustc", /x/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/rustc, "--cargo-lockfile", /y/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------

error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/x/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/rustc - --crate-name ___ --print=file-names --target aarch64-unknown-nto-qnx710 --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "aarch64-unknown-nto-qnx710". Run `rustc --print target-list` for a list of built-in targets


Error: Failed to run cargo tree: exit status: 101
```

**Pull request merged**
