### PR TITLE
Release 0.39.0

### PR DESCRIPTION
**Pull request by freeformstu**

### CODE REVIEW

**Comment by krasimirgg** [comment]
Could you add details on which changes are we picking up in this version.

**Comment by UebelAndre** [comment]
> Could you add details on which changes are we picking up in this version.

That’s autogenerated in the release notes. Or maybe I’m confused by what you’re looking for.

**Comment by krasimirgg** [comment]
> > Could you add details on which changes are we picking up in this version.
> 
> That’s autogenerated in the release notes. Or maybe I’m confused by what you’re looking for.

I just assumed there are some new API changes incompatible with 0.38? Or it's more of a: release at a regular time intervals?

**Comment by UebelAndre** [comment]
rules_rust releases are intended to be regular interval things

**Review by UebelAndre — APPROVED** [review]

**Pull request merged**
