### PR TITLE
Enable xz archives

### PR DESCRIPTION
**Pull request by wt**
XZ archives are about half the size of the gz equivalents. This
improves the cold repo bootstrap case a fair amount.

Fixes: #871

### CODE REVIEW

**Comment by wt** [comment]
The static rust environment variable is interfering with this since the url it adds ends up on the top of the list. I have removed it. It's not clear to me that the functionality is super useful since the default location for urls matches it. If it's needed, I would love some suggestions for how to deal with it.

**Comment by uhthomas** [comment]
Is it possible to use `tar.zst` instead?

Arch Linux switched from xz to zst because it decompresses significantly faster (~1300%), at the cost of slightly larger archives (~0.8%).

**Comment by wt** [comment]
Are zstd archives supported by bazel? If so, the diff from here to there would be pretty small. There doesn't appear to be a programatic list of the archive types supported, so each much be added manually.

Assuming that is done, at the very least you can supply the sha256s manually to the register_rust_toolchains function.

Having said that, tar.zstd are not available from the rust distribution that I could find. Nothing would stop you from downloading an xz file and converting it to use zstd compression and distributing them from a web site.

**Comment by uhthomas** [comment]
>Are zstd archives supported by bazel?

Yep! :) The list of supported archives can be found with the [http_archive](https://bazel.build/rules/lib/repo/http#http_archive) documentation.

>It supports the following file extensions: "zip", "jar", "war", "aar", "tar", "tar.gz", "tgz", "tar.xz", "txz", "tar.zst", "tzst", tar.bz2, "ar", or "deb".

>Having said that, tar.zstd are not available from the rust distribution that I could find. 

That is a shame, though I thought this might be the case. Thank you for considering my suggestion.

**Comment by wt** [comment]
Find the files for download and it would be easy to add them to the fold. BTW, those archive formats are buried in many comments around bazel. It would be truly awesome if they were available programatically for extensions. If you wanted to create an issue to ask for that on the main bazel repo, feel free to tag me.

Also, if you can find the location of the .tar.zst files. The additional diff on top of this one would be pretty small.

**Review by illicitonion — APPROVED** [review]
Thanks!

**Comment by UebelAndre** [comment]
Cross posting from https://github.com/bazelbuild/rules_rust/commit/841fc6fb82141576d91aecb1d3f2656d58b0ab71#commitcomment-72310891 to try and consolidate info on the PR.

cc @krasimirgg @wt

**Pull request merged**
