### PR TITLE
Fix transitive duplicate deps in proc macros

### LINKED ISSUE #1258: third party dependency libraries do are not properly disambiguated when the exec and target configurations are used
Hello! I am running into a problem only in linux, build is fine in mac osx. The error I am seeing looks like this:

```
  = note: /usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-648849910.a(bio_ssl.o): multiple definition of 'BIO_f_ssl'
          /usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-944345047.a(bio_ssl.o): previous definition here
          /usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-648849910.a(bio_ssl.o): multiple definition of 'BIO_new_ssl'
          /usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-944345047.a(bio_ssl.o): previous definition here
          # hundreds of lines of similar output
 ```
 
 It appears that ambiguous libs are being linked from `fastbuild` and the `opt-exec`. Any thoughts on what could be causing this? These libs are coming from openssl, which I have copied verbatim from the examples directory in this repo. When I cd into the repo containing the issue I see this:
 
 ```
lrwxrwxrwx 1 root root  100 Apr 13 07:16 libcrypto-778601226.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-fastbuild/bin/external/openssl/openssl/lib/libcrypto.a
lrwxrwxrwx 1 root root  108 Apr 13 07:17 libcrypto-808729207.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/openssl/openssl/lib/libcrypto.a
lrwxrwxrwx 1 root root  105 Apr 13 07:17 libssl-648849910.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/openssl/openssl/lib/libssl.a
lrwxrwxrwx 1 root root   97 Apr 13 07:16 libssl-944345047.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-fastbuild/bin/external/openssl/openssl/lib/libssl.a
 ```

### PR DESCRIPTION
**Pull request by tzilist**
Closes #1258

### CODE REVIEW

**Review by scentini — COMMENTED** [review]
Thanks for the PR! Could we also add a test akin to the one added in https://github.com/bazelbuild/rules_rust/pull/1206?

**Comment by UebelAndre** [comment]
@tzilist Friendly ping on this one 😄. Is there anything the maintainers can do to help?

**Comment by tzilist** [comment]
@UebelAndre So sorry, life has caught me off guard for the last few weeks! It seems the next step would be to write some tests, however, I am not exactly sure what I should be testing. Is there any way one of the maintainers can write the tests up for this PR? Very sorry to dump this on all of you :(

**Comment by UebelAndre** [comment]
@scentini does anyone on your team have bandwidth to take this over the finish-line?

**Comment by scentini** [comment]
Sure, I put together https://github.com/bazelbuild/rules_rust/pull/1359.

**Comment by UebelAndre** [comment]
> @UebelAndre So sorry, life has caught me off guard for the last few weeks! It seems the next step would be to write some tests, however, I am not exactly sure what I should be testing. Is there any way one of the maintainers can write the tests up for this PR? Very sorry to dump this on all of you :(

Hey, life happens, no need to be sorry of feel bad. Thanks so much for putting up the PR and we wish you the best!

> Sure, I put together #1359.

And thank you @scentini for putting up https://github.com/bazelbuild/rules_rust/pull/1359!

**Pull request closed without merging**
