### PR TITLE
Fix crate deps with condition

### LINKED ISSUE #1880: Cargo.toml with conditions are failing to build
I have this section in my Cargo.toml

```
[target.'cfg(target_os = "macos")'.dependencies]
 security-framework = "2.8.0"
```

and it's generating errors:

```
                aliases = aliases(),
        File "/private/var/tmp/_bazel_yuweiba/f3b87d172301024018ed3e9f856c70fc/external/crate_index/defs.bzl", line 281, column 30, in aliases
                if condition_triples in crate_aliases:
Error: unhashable type: 'list'
```

I think this is essentially from: https://github.com/bazelbuild/rules_rust/blob/d6e3003594713ba00d03a354cbf7a7c2c65e22d2/proto/3rdparty/crates/defs.bzl#L362

which is generated from https://github.com/bazelbuild/rules_rust/blob/d6e3003594713ba00d03a354cbf7a7c2c65e22d2/crate_universe/src/rendering/templates/module_bzl.j2#L317

I tried casting the list to tuples but it still fails with some other errors.

so not sure best way to fix this?

### PR DESCRIPTION
**Pull request by ibigbug**
Fixed #1880

### CODE REVIEW

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Thanks! Is this something you'd be able to add an integration test for at https://github.com/bazelbuild/rules_rust/tree/0.19.1/examples/crate_universe? I thought the alias example there would have caught an issue like this but it's clearly lacking. Could you update this so we don't have aliases break again in the future?

**Comment by ibigbug** [comment]
sure I'll add it. but sorry for the confusion I think we still need some polish to this PR https://github.com/bazelbuild/rules_rust/issues/1880#issuecomment-1483128569

**Comment by ibigbug** [comment]
@UebelAndre I think I made some progress, and got a new error

```
DEBUG: /private/var/tmp/_bazel_yuweiba/f3b87d172301024018ed3e9f856c70fc/external/crate_index/defs.bzl:276:10: {"": {}, "cfg(target_os = \"macos\")": {}}
DEBUG: /private/var/tmp/_bazel_yuweiba/f3b87d172301024018ed3e9f856c70fc/external/crate_index/defs.bzl:276:10: {"": {}}
ERROR: /Users/yuweiba/workspace/projects/clash-rs/clash/BUILD.bazel:4:13: //clash:aarch64-apple-darwin is not a valid select() condition for //clash:lib.
To inspect the select(), run: bazel query --output=build //clash:lib.
For more help, see https://docs.bazel.build/be/functions.html#select.
```

any suggestions where to go next step?

**Comment by ibigbug** [comment]
@UebelAndre sorry i wasn't able to make any progress. do you have any suggestions?

**Comment by k1nkreet** [comment]
> @UebelAndre I think I made some progress, and got a new error
> 
> ```
> DEBUG: /private/var/tmp/_bazel_yuweiba/f3b87d172301024018ed3e9f856c70fc/external/crate_index/defs.bzl:276:10: {"": {}, "cfg(target_os = \"macos\")": {}}
> DEBUG: /private/var/tmp/_bazel_yuweiba/f3b87d172301024018ed3e9f856c70fc/external/crate_index/defs.bzl:276:10: {"": {}}
> ERROR: /Users/yuweiba/workspace/projects/clash-rs/clash/BUILD.bazel:4:13: //clash:aarch64-apple-darwin is not a valid select() condition for //clash:lib.
> To inspect the select(), run: bazel query --output=build //clash:lib.
> For more help, see https://docs.bazel.build/be/functions.html#select.
> ```

I've got to the same issue with my small research on this topic. It looks like the problem is `module_bzl.j2` defining `_CONDITIONS` value uses triples from `context.conditions` holding the values which are not transformed with `platforms_template`. I'm not really familiar with the tool  processing those templates to understand whether it's possible to apply `platforms_template` to `triples` inside the template specification. The other option could be to provide additional value in `context` or change the value of `context.conditions` according to `platforms_template`. I wonder if @UebelAndre do you has any thoughts on that

**Comment by k1nkreet** [comment]
Since I've spent some time tinkering on `cargo-bazel-bin` tool to solve the last issue and I've made some progress on it, I took the liberty of opening [the new PR](https://github.com/bazelbuild/rules_rust/pull/2018) where I've added the integration test/example, took the changes from this PR and added fix [this](https://github.com/bazelbuild/rules_rust/pull/1901#issuecomment-1492029546) problem

**Pull request closed without merging**
