### PR TITLE
Add sysroot support to build.rs scripts.

### PR DESCRIPTION
**Pull request by sayrer**
If there's a sysroot, it needs to appear before any other flags. See: #659.

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]
Thanks!

**Comment by hlopko** [comment]
Could you add a unit test? Hopefully https://github.com/bazelbuild/rules_rust/pull/608 is a good starting example?

**Comment by sayrer** [comment]
> Could you add a unit test? Hopefully #608 is a good starting example?

I'm not really certain how I would add a unit test for this, at least in that style. This patch doesn't change the analysis. I think I'd have to run the binary and check that the sysroot appeared in the command output, since all this does is put the sysroot into an environment variable for use with the binary target.

It might be better to check in a copy of *ring*, or something similarly complicated, and build it with a sysroot.

**Comment by hlopko** [comment]
Yeah you're right, using a cc toolchain with a sysroot in a unittest is hard. Ignore my comment. @illicitonion can you merge this PR (since you approved and didn't merge I don't want to step in)?

**Comment by illicitonion** [comment]
I thought I pressed the merge button when I approved! ... Weird.

**Comment by illicitonion** [comment]
Oh, looks like I don't have permission to merge main - @sayrer could you rebase/merge main and I'll merge to main? Thanks!

**Comment by sayrer** [comment]
Huh, now I'm getting Buildkite complaints about files that aren't in my patch. Will take a look later on today.

**Comment by UebelAndre** [comment]
Seems like buildifier was fixed 😄

**Comment by sayrer** [comment]
Put up #675. It seems like I just got unlucky here.

**Comment by hlopko** [comment]
And we'll need a merge again :/

**Comment by hlopko** [comment]
Thank you!

**Pull request merged**
