### PR TITLE
Update to Rust Compiler 1.26.1

### PR DESCRIPTION
**Pull request by damienmg**

### CODE REVIEW

**Comment by nlopezgi** [comment]
We recently started testing rules_rust with Bazel remote execution. This PR brakes builds with remote execution with the following message:
ERROR: /<...>/external/examples/hello_out_dir/BUILD:10:1: Couldn't build file external/examples/hello_out_dir/libhello_out_dir-2007309047.rlib: error executing shell command: 'set -e; if [ ! -z "${TMPDIR+x}" ]; then mkdir -p $TMPDIR; fi; rm -rf bazel-out/k8-fastbuild/bin/external/examples/hello_out_dir/hello_out_dir.deps; mkdir bazel-out/k8-fastbuild/bin/external/example...' failed (Exit 101): bash failed: error executing command 
  (cd /<...>/execroot/io_bazel_rules_rust && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    PATH=/bin:/usr/bin \
  /bin/bash -c 'set -e; if [ ! -z "${TMPDIR+x}" ]; then mkdir -p $TMPDIR; fi; rm -rf bazel-out/k8-fastbuild/bin/external/examples/hello_out_dir/hello_out_dir.deps; mkdir bazel-out/k8-fastbuild/bin/external/examples/hello_out_dir/hello_out_dir.deps
 mkdir ./out_dir/
 tar -xzf external/examples/hello_out_dir/repacked_srcs.tar.gz -C ./out_dir
 CARGO_PKG_VERSION=0.0.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=0 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE= CARGO_PKG_AUTHORS= CARGO_PKG_NAME=hello_out_dir CARGO_PKG_DESCRIPTION= CARGO_PKG_HOMEPAGE= LD_LIBRARY_PATH=external/rust_linux_x86_64/rustc/lib DYLD_LIBRARY_PATH=external/rust_linux_x86_64/rustc/lib OUT_DIR=$(pwd)/out_dir external/rust_linux_x86_64/rustc/bin/rustc external/examples/hello_out_dir/src/lib.rs --crate-name hello_out_dir --crate-type rlib --codegen opt-level=3 --codegen metadata=-2007309047 --codegen extra-filename='\''-2007309047'\'' --codegen ar=/usr/bin/ar --codegen linker=/usr/local/bin/clang --codegen link-args='\'''\'' --out-dir bazel-out/k8-fastbuild/bin/external/examples/hello_out_dir --emit=dep-info,link --color always -L all=external/rust_linux_x86_64/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib')
error: failed to find a `codegen-backends` folder in the sysroot candidates:

found a thread with similar error message: https://github.com/rust-lang-nursery/rust-clippy/issues/2573
States that "You are probably missing 'codegen-backends/librustc_trans-llvm.so'"
I searched for the file and it is present in the rules_rust external repo, but if its not making it to the remote exec enviroment its likely not properly declared as a dependency. 
Error is likely possible to reproduce with local docker sandboxing available with bazel 0.14.1 (or contact me for repro instructions)

**Comment by damienmg** [comment]
Ni Nicolas,

How can we repro? the docker spawn strategy doesn't seem to work:

```
$ bazel build --spawn_strategy=docker --experimental_docker_image=ubuntu:18.04 @examples//...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
..........
ERROR: 'docker' is an invalid value for docker spawn strategy. Valid values are: linux-sandbox, local, processwrapper-sandbox, sandboxed,
standalone, worker
INFO: Elapsed time: 1.436s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded)
```

To be fair I am not even sure the docker strategy would do the right things since the sandboxed strategy still seems to see that file.

**Comment by nlopezgi** [comment]
Hi Damien,
Local docker sandbox is built to catch issues that are not caught with the current sandboxed strategy, so I'm not surprised builds work with that fine. 

In order to use the docker strategy you need to use bazel 0.14.1, and add multiple flags to your build:
--experimental_enable_docker_sandbox
--experimental_docker_verbose
spawn_strategy=docker --strategy=Javac=docker --genrule_strategy=docker
--experimental_docker_image=gcr.io/cloud-marketplace/google/rbe-ubuntu16-04@sha256:59bf0e191a6b5cc1ab62c2224c810681d1326bad5a27b1d36c9f40113e79da7f
--define=EXECUTOR=remote
--crosstool_top=@bazel_toolchains//configs/ubuntu16_04_clang/1.0/bazel_0.13.0/default:toolchain

Note this build will run using the rbe-ubuntu16-04 toolchain container.
Note the crosstool_top flag is pointing to bazel-toolchains repo, so you would need to add that to your WORKSPACE (https://releases.bazel.build/bazel-toolchains.html). 

I will send you more detailed instructions that I plan to make public very soon.

**Comment by damienmg** [comment]
Thanks for the info. For some reason the [blog post](https://blog.bazel.build/2018/06/01/bazel-0.14.html) does not mention `--experimental_enable_docker_sandbox`.

**Comment by damienmg** [comment]
And still the same issue:
```
 $ bazel test --config local-docker @examples//...
ERROR: 'docker' is an invalid value for docker spawn strategy. Valid values are: linux-sandbox, local, processwrapper-sandbox, remote, sandboxed, standalone, worker
INFO: Elapsed time: 0.270s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

(using the rc file you send me by mail)

**Comment by damienmg** [comment]
Also:
```
$ bazel version
Build label: 0.14.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 8 12:17:35 2018 (1528460255)
Build timestamp: 1528460255
Build timestamp as int: 1528460255
```

This is on my workstation but my other test was on my personal laptop with 0.14.1

**Comment by nlopezgi** [comment]
Can you try running the build from inside a docker container as I indicated in the second method of the doc I sent you. There might be permission issues related to how docker is setup in your machine that you should be able to circumvent with that method.

**Comment by damienmg** [comment]
Unsurprisingly this also give the same error. The strategy docker is not defined.

**Comment by nlopezgi** [comment]
Are you running the build with --experimental_docker_verbose? Could you copy here the full error message you get so I can hep debug? Sorry for the issues, we're still testing out the docker feature and ironing out issues.

**Comment by damienmg** [comment]
The output I gave is the full output. It's running with the given Bazelrc. Visibly Bazel 0.14.1 doesn't have the docker strategy in it.

**Comment by nlopezgi** [comment]
That is quite odd as I ran the instructions I sent you right before sending them your way without any issues. Are you installing the bazel version using the bazel installer? I am using the installer in this location:
https://releases.bazel.build/0.14.1/release/bazel-0.14.1-installer-linux-x86_64.sh
with this sha256:
7b14e4fc76bf85c4abf805833e99f560f124a3b96d56e0712c693e94e19d1376
That prints out this info with bazel version:
Build label: 0.14.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 8 12:17:35 2018 (1528460255)
Build timestamp: 1528460255
Build timestamp as int: 1528460255
(same as yours, it seems) and just re-ran a command inside the docker container without any issues.
Are you following the instructions I sent to run inside a docker container exactly as I sent them or changing them in any way (so that I can try to reproduce your error)?
What is the result of running docker ps inside the container?
What is the result of running whoami in the container (should be root)?
Sorry again for the issues, but the feature is available with Bazel 0.14.1 and there is something in your setup that is not allowing you to properly run with this feature.

**Comment by damienmg** [comment]
The docker image is a slight variation of the cirrusci but running as root
should not be a requirement. If I try with Bazel head I get a stacktrace. I
definitely run the same version of Bazel. I'll retry with the same docker
file but this is highly confusing is the problem is an access to the docker
daemon.

**Comment by nlopezgi** [comment]
The problem is likely related to access to the docker deamon, as you mention, (that is why I asked about base image and user). The dockerfile I included in the doc has instructions specifically to set up docker for that base image (debian:stretch), so it would not be surprising if it does not run in other base images. Any particular reason why you are using the cirrusci image and not the debian:stretch image to launche the bazel build (as this is being used as a host container, it should not matter what base image you use)? Could you please try with the debian:stretch base image to see if that works for you?

**Comment by damienmg** [comment]
I am trying with the debian stretch. I had 0.14.1 on a Cirrus based image
that was simpler for me. I am testing on my personal laptop so I have to
copy everything by hand and the less I copy the better ;)

**Comment by damienmg** [comment]
This is working indeed. It's a really bad error message, it looks like the option doesn't exists...

**Comment by nlopezgi** [comment]
Thanks Damien, I'll get this feedback to folks working on this feature so we can get better error messaging, good to know that you should be able to continue your debugging.

**Comment by damienmg** [comment]
Bazel HEAD is crashing with the following stacktrace:
```
Starting local Bazel server and connecting to it...
...................
ERROR: Docker sandboxing is disabled, because running 'docker info' failed: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
	at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:82)
	at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
	at com.google.devtools.build.lib.sandbox.DockerSandboxedSpawnRunner.isSupported(DockerSandboxedSpawnRunner.java:116)
	at com.google.devtools.build.lib.sandbox.SandboxModule.setup(SandboxModule.java:170)
	at com.google.devtools.build.lib.sandbox.SandboxModule.executorInit(SandboxModule.java:114)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.<init>(ExecutionTool.java:136)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:168)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:345)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:75)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR: 'docker' is an invalid value for docker spawn strategy. Valid values are: linux-sandbox, local, processwrapper-sandbox, remote, sandboxed, standalone, worker
INFO: Elapsed time: 1.533s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded)
```

And the issue is that my laptop is new and I recently installed docker I probably need to restart my session to get the permission corrected.

**Comment by damienmg** [comment]
Fixing the docker permission and now it works fine from my host machine.
I'll get a fix today or tomorrow.

**Pull request merged**
