### PR TITLE
Test the examples on Bazel's CI

### PR DESCRIPTION
**Pull request by philwo**

### CODE REVIEW

**Comment by damienmg** [comment]
Here what I did to fix the tests on my machines (the bindgen tests doesn't pass because of some configuration issue):

```
$ git diff
diff --git a/examples/WORKSPACE b/examples/WORKSPACE
index 0603384..8c6a44a 100644
--- a/examples/WORKSPACE
+++ b/examples/WORKSPACE
@@ -1,26 +1,34 @@
 workspace(name = "examples")
 
-local_repository(name = "io_bazel_rules_rust", path = "..")
+load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
+
+local_repository(
+    name = "io_bazel_rules_rust",
+    path = "..",
+)
 
 load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
+
 rust_repositories()
 
 new_git_repository(
     name = "libc",
+    build_file = "libc.BUILD",
     remote = "https://github.com/rust-lang/libc",
     tag = "0.2.20",
-    build_file = "libc.BUILD",
 )
 
 load("@io_bazel_rules_rust//proto:repositories.bzl", "rust_proto_repositories")
+
 rust_proto_repositories()
 
 http_archive(
     name = "bazel_skylib",
-    url = "https://github.com/bazelbuild/bazel-skylib/archive/0.5.0.tar.gz",
-    sha256 = "b5f6abe419da897b7901f90cbab08af958b97a8f3575b0d3dd062ac7ce78541f",
-    strip_prefix = "bazel-skylib-0.5.0"
+    sha256 = "eb5c57e4c12e68c0c20bc774bfbc60a568e800d025557bc4ea022c6479acc867",
+    strip_prefix = "bazel-skylib-0.6.0",
+    url = "https://github.com/bazelbuild/bazel-skylib/archive/0.6.0.tar.gz",
 )
 
 load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")
+
 bazel_version(name = "bazel_version")
diff --git a/examples/ffi/c_calling_rust/BUILD b/examples/ffi/c_calling_rust/BUILD
index 3c6367b..312a3e5 100644
--- a/examples/ffi/c_calling_rust/BUILD
+++ b/examples/ffi/c_calling_rust/BUILD
@@ -1,4 +1,4 @@
-load("@//rust:rust.bzl", "rust_binary", "rust_library", "rust_test")
+load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary", "rust_library", "rust_test")
 
 rust_library(
     name = "rusty",
diff --git a/examples/ffi/rust_calling_c/BUILD b/examples/ffi/rust_calling_c/BUILD
index eb49a4d..16ec03b 100644
--- a/examples/ffi/rust_calling_c/BUILD
+++ b/examples/ffi/rust_calling_c/BUILD
@@ -1,6 +1,6 @@
 package(default_visibility = ["//ffi/rust_calling_c:__subpackages__"])
 
-load("@//rust:rust.bzl", "rust_library", "rust_test", "rust_binary", "rust_doc")
+load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library", "rust_test", "rust_binary", "rust_doc")
 
 rust_library(
     name = "matrix",
```

So there is 2 more labels that are incorrect and skylib needs to be bumped. If you want I can push that on top of your PR or you can integrate the change yourself.

**Comment by philwo** [comment]
@damienmg Thanks for the patch! I'll integrate it and see that I can get the tests passing :)

**Comment by damienmg** [comment]
And now I got all the test passing on my machine with adding the following:

+load("@io_bazel_rules_rust//bindgen:repositories.bzl",
"rust_bindgen_repositories")
+
+rust_bindgen_repositories()
+

**Comment by philwo** [comment]
I'm still fighting with the libc in my WORKSPACE that doesn't seem to work (even tried replacing the `new_git_repository` with an `http_archive`, but am getting the same error).

I tried to copy the `libc.BUILD` from the top-level workspace to the examples workspace, because it was missing there, but now I'm getting this:

```
ERROR: /Users/philwo/src/rules_rust/examples/ffi/rust_calling_c/BUILD:29:1: no such package '@libc//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_philwo/950140b41fdb1a69bb14157d1578bb2c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_philwo/950140b41fdb1a69bb14157d1578bb2c/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 62, in workspace_and_buildfile
		ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: /Users/philwo/src/rules_rust/examples/external/libc.BUILD and referenced by '//ffi/rust_calling_c:matrix_dynamically_linked'
```

Do you remember if you did something to make that work?

**Comment by damienmg** [comment]
Thanks!

**Comment by philwo** [comment]
Yay, all green!

@damienmg Thanks for the hints. :)

**Pull request merged**
