### PR TITLE
rustdoc: respect error_format config

### PR DESCRIPTION
**Pull request by goffrie**
This makes it easier to make a test ensuring rustdoc doesn't emit warnings.

### CODE REVIEW

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Hi, thanks for the PR! Can you provide a bit more context here as well as a unit test of sorts?

**Comment by goffrie** [comment]
The context is that we have automation using the output of rustdoc that uses json error format. We used to use extra rustc flags to pass `--error-format=json` but that broke since #1275 now unconditionally passes `--error-format=human` to rustdoc (and it's an error to specify error-format twice on the rustc/rustdoc command line). I figured that the cleaner solution would be to respect the global error_format configuration instead of trying to revert the old change.

I'll see when I can find some time to work on a unit test, but this isn't urgent to merge since we run a patched version.

**Review by UebelAndre — CHANGES_REQUESTED** [review]
In https://github.com/bazelbuild/rules_rust/blob/0.27.0/test/unit/rustdoc/rustdoc_unit_test.bzl you should be able to add a test that hard codes some value for `//:error_format` that you should be able to assert made it's way into the resulting action. 

Does that seem reasonable?

**Comment by goffrie** [comment]
Thanks for the pointer! I've added a test - is that what you had in mind?

**Review by UebelAndre — APPROVED** [review]
This is perfect, thank you!

**Pull request merged**
