### PR TITLE
Update repository rules to supported versions

### LINKED ISSUE #93: Please move from native to Skylark rules for external git/http repositories
Bazel is planning to move away from native rules for external repositories to Skylark rules, mainly because bundling every version control system in bazel does not scale. As part of this effort, we plan to submit https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause bazel by default to insist that the skylark versions the git and http rules for external repositories be used. This can be disabled by a flag for at least the next 6 months, but we still would appreciate if you could adopt your repository to use the Skylark versions of those rules soon.

A test run of downstream projects with that flag flip in bazel enabled can be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

### PR DESCRIPTION
**Pull request by dslomov**
Fixes #93.

### CODE REVIEW

**Comment by mfarrugi** [comment]
Flaky build? Link gives me a 404. 

Are we still prevented from moving this into the examples workspace?

**Comment by dslomov** [comment]
Build fixed, sorry about that.

> Are we still prevented from moving this into the examples workspace?

I am not quite sure what you refer to, sorry - can you explain?

**Comment by mfarrugi** [comment]
Looks like it's still unhappy. I was talking about the Todo on https://github.com/bazelbuild/rules_rust/blob/master/WORKSPACE#L13 but it doesn't need to be addressed here regardless.

**Comment by dslomov** [comment]
Ok 3rd time's the charm (I hope). I didn't realize the root does not have a BUILD file.

**Pull request merged**
