### PR TITLE
refactored `rust_toolchain` into `rust_exec_toolchain` and `rust_target_toolchain`

### PR DESCRIPTION
**Pull request by UebelAndre**
Required pull-requests:
- https://github.com/bazelbuild/rules_rust/pull/805
- https://github.com/bazelbuild/rules_rust/pull/803
- https://github.com/bazelbuild/rules_rust/pull/802
- https://github.com/bazelbuild/rules_rust/pull/799
- https://github.com/bazelbuild/rules_rust/pull/798
- https://github.com/bazelbuild/rules_rust/pull/797
- https://github.com/bazelbuild/rules_rust/pull/795
- https://github.com/bazelbuild/rules_rust/pull/794
- https://github.com/bazelbuild/rules_rust/pull/793
- https://github.com/bazelbuild/rules_rust/pull/792
- https://github.com/bazelbuild/rules_rust/pull/773

### CODE REVIEW

**Comment by UebelAndre** [comment]
Just so everyone's aware of where all the PRs came from. I've been working on refactoring the toolchains so it's easier to register target toolchains for cross-compilation. There's still some rough edges here but the gist of this is the previous `rust_toolchain` has been split into `exec` and `target` variants where `exec` contains the compiler and things and `target` contains all the linkable libraries for the target platform. This is largely inspired by https://github.com/bazelbuild/rules_rust/issues/523 and a conversation that was had in slack. As the other PRs get closed out, I'll be making minor changes here and adding documentation.

**Comment by hlopko** [comment]
I'm concerned that the approach you're taking may not be the best possible. Could you first start a discussion about:

* what you're trying to achieve?
* why is it important?
* how do you want to achieve it?

Whenever there is a big "chunk" of work that requires so many changes we should get into a habit of discussing the general approach first, and only starting coding afterwards. It's very frustrating to the author to receive substantial feedback in the middle of the "project" that invalidates prior work. Communicating up front makes it easier for the reviewers to understand the context and motivation behind changes.

**Comment by UebelAndre** [comment]
> I'm concerned that the approach you're taking may not be the best possible. Could you first start a discussion about:
> 
>     * what you're trying to achieve?
> 
>     * why is it important?
> 
>     * how do you want to achieve it?
> 
> 
> Whenever there is a big "chunk" of work that requires so many changes we should get into a habit of discussing the general approach first, and only starting coding afterwards. It's very frustrating to the author to receive substantial feedback in the middle of the "project" that invalidates prior work. Communicating up front makes it easier for the reviewers to understand the context and motivation behind changes.

This work was inspired by a slack thread with @jmillikin where he shared a [great blog](https://john-millikin.com/notes-on-cross-compiling-rust#bazel) which showed cross-compilation with `rules_rust` and shows how the existing format of the toolchains/toolchain-repositories can be clunky. I typically open drafts for folks to provide high-level feedback if they're interested but until it's moved to a pull-request, it's not ready for review. I also enjoy having a demo of something mildly working when having design discussions to keep them guided. I intended this draft to act as that guide when I got around to finally writing it up (not trying to circumvent feedback 😅).

**Comment by UebelAndre** [comment]
I've created a discussion for this PR: https://github.com/bazelbuild/rules_rust/discussions/815

**Comment by UebelAndre** [comment]
Closing this based on https://github.com/bazelbuild/rules_rust/discussions/815#discussioncomment-2055378

**Pull request closed without merging**
