### PR TITLE
Enable buildifier for CI

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Comment by UebelAndre** [comment]
@damienmg @mfarrugi Any assistance in solving for these warnings would be greatly appreciated! 🙏 

I think it'd be really good for the repo to have `buildifier` enabled 😅

**Comment by mfarrugi** [comment]
I don't think either of us are up for making changes. It would be a
step-forward to disable the complaints, then more complaints won't slip
through.

**Comment by UebelAndre** [comment]
I opened #443 and #442 to track things I feel really should be solved

**Comment by UebelAndre** [comment]
I also opened #441 to solve for additional defects not caught in CI (I believe this is due to how the example's workspaces are setup)

**Pull request merged**
