### PR TITLE
Cut loading time deps of the import macro

### PR DESCRIPTION
**Pull request by hlopko**
Fixes https://github.com/bazelbuild/rules_rust/issues/1166.

### CODE REVIEW

**Comment by wt** [comment]
This does not fix #1166

**Comment by hlopko** [comment]
(continuing on the issue: https://github.com/bazelbuild/rules_rust/issues/1166#issuecomment-1061485802)

**Review by illicitonion — APPROVED** [review]
Worked for me, and taught me about a whole new feature of Bazel I didn't know about - thanks so much!

**Comment by wt** [comment]
Now that the main branch has been merged into your branch, this seems to fix the problem. When I reported that it wasn't fixed, your branch on github didn't include the merge of main.

**Comment by wt** [comment]
I think I just managed to sync your branch before the merge was in there. Anyway, it does seem to work now.

**Pull request merged**
