### PR TITLE
Generate valid file if no crates are found

### PR DESCRIPTION
**Pull request by illicitonion**
Currently we get an error about bad indentation

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]

**Comment by UebelAndre** [comment]
Thanks!

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Actually, could you add a new example for this? To catch any regressions 🙏

**Comment by illicitonion** [comment]
Added a unit test instead :)

**Review by UebelAndre — APPROVED** [review]
Nice! Thanks for adding the test!

**Pull request merged**
