### PR TITLE
Moved rust extension rules into a separate `rules_rust_ext` workspace.

### PR DESCRIPTION
**Pull request by UebelAndre**
This change moves the `bindgen`, `proto`, and `wasm_bindgen` sub-packages into individual workspaces within the `extensions` directory. The intent is improve ease of maintenance of both core and extension Rust rules by ensuring changes to extensions have no impact on the core rules. Core rules should *never* depend on extensions.

Load statements should be updated according to the following table:

| before | after |
| --- | --- |
| `@rules_rust//bindgen` | `@rules_rust_bindgen//` |
| `@rules_rust//proto/prost` | `@rules_rust_prost//` |
| `@rules_rust//proto/protobuf` | `@rules_rust_protobuf//` |
| `@rules_rust//wasm_bindgen` | `@rules_rust_wasm_bindgen//` |

closes https://github.com/bazelbuild/rules_rust/issues/2882

### CODE REVIEW

**Comment by UebelAndre** [comment]
@illicitonion @krasimirgg @hlopko I would love your input on this change. It's a massive breaking change but I think a better path forward to help ensure the `protobuf`/`rules_cc` headache from https://github.com/bazelbuild/rules_rust/pull/2998 doesn't impact the core rules again.

**Comment by krasimirgg** [comment]
Thank you I think it looks very reasonable, but also I'm not working in an environment where rules_rust+bzlmod is exercised, so it's hard to flag potential non-trivial issues with this. I just asked a few folks to take a look at this and share their thoughts.

**Comment by konkers** [comment]
Curious about the motivation to put them all into a single `@rules_rust_ext` module.  I would have naively expected them to have separate modules (i.e. `@rules_rust_bindgen`, `@rules_rust_prost`, etc.)   That way a project would have more fined grained control over it's dependencies.

**Comment by UebelAndre** [comment]
> Curious about the motivation to put them all into a single `@rules_rust_ext` module. I would have naively expected them to have separate modules (i.e. `@rules_rust_bindgen`, `@rules_rust_prost`, etc.) That way a project would have more fined grained control over it's dependencies.

I started down that path and hit the 80 job cap for BazelCI. For each extension I would want to test them on Linux, Linux RBE, MacOS, and Windows, and to have each product be it's own workspace didn't seem possible. Though @meteorcloudy maybe there's a way to raise that cap?

**Review by illicitonion — APPROVED** [review]
Happy to do this, equally happy to have a per-extension module if that's practical :) Thanks for doing the work!

**Review by krasimirgg — APPROVED** [review]
Thank you! Looks good (if we manage to solve the testing CI limit situation, splitting this up more would be good too).

**Comment by UebelAndre** [comment]
The commit I just added splits the extensions into their own repositories but hits the following error:

https://buildkite.com/bazel/rules-rust-rustlang/builds/12747#0193646f-6c25-4faa-a809-e5e319a1c9e6
```
The number of tasks in one config file is limited to 80!
fatal: pipeline parsing of "(stdin)" failed: EOF
```

@meteorcloudy @krasimirgg there's no way to raise this is there 😅

(Plus, it would be nice to be told how many were found)

**Comment by meteorcloudy** [comment]
presubmit is now working https://buildkite.com/bazel/rules-rust-rustlang/builds/12752

**Comment by UebelAndre** [comment]
> presubmit is now working https://buildkite.com/bazel/rules-rust-rustlang/builds/12752

With this in place I'll go ahead and update the PR to reflect the granular workspaces change instead of `rules_rust_ext`.

**Pull request merged**
