### PR TITLE
Use short_path for runfiles tree references

### PR DESCRIPTION
**Pull request by kchodorow**
This fixes the rust tests on ci.bazel.io.

### CODE REVIEW

**Comment by kchodorow** [comment]
I'm not sure what's up the CLA, I think I'm in some sort of merge hell.

**Comment by damienmg** [comment]
Seems like an issue when you rebased.

**Comment by kchodorow** [comment]
Okay, after some rebasing, force pushing, and mucking with the reflog, I think this is good to go.

**Comment by davidzchen** [comment]
LGTM

**Pull request merged**
