### PR TITLE
Fix @libgit2

### PR DESCRIPTION
**Pull request by uhthomas**
The include prefix for "src/" was not stripped correctly.

### CODE REVIEW

**Comment by uhthomas** [comment]
Fixed #1456

**Comment by uhthomas** [comment]
Not sure. It could be some configuration in our .bazelrc which makes things worse.

It just seemed like the headers weren't linked and so would fall back to system headers. Specifically in the case of regexp.h it will error unconditionally.

https://sourceware.org/bugzilla/show_bug.cgi?id=18681

**Comment by UebelAndre** [comment]
Thanks for putting this together!

**Comment by uhthomas** [comment]
Happy to help.

**Pull request merged**
