### PR TITLE
Add support for split_coverage_post_processing

### PR DESCRIPTION
**Pull request by UebelAndre**
This change introduces `experimental_use_coverage_metadata_files` (https://github.com/bazelbuild/rules_rust/issues/2082) which is required to support [--experimental_split_coverage_postprocessing](https://bazel.build/reference/command-line-reference#flag--experimental_split_coverage_postprocessing)'

Changes:
- Implemented coverage collection logic in Rust.
- Added a flag `--@rules_rust//rust/settings:experimental_use_coverage_metadata_files` to toggle the changes necessary for supporting `--experimental_split_coverage_postprocessing`.
- Added regression testing in CI to test `--experimental_split_coverage_postprocessing`.

### CODE REVIEW

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/bazel/pull/18634 is required as `rules_rust` currently only supports llvm based coverage and utilizes the same `collect_cc_coverage` attr hook.

**Comment by UebelAndre** [comment]
Seeing some odd timeouts on some tests: https://buildkite.com/bazel/rules-rust-rustlang/builds/8718#0188ad81-d635-4fc5-be1a-cb4c1222f476

@illicitonion wondering if you have any ideas as to what might be causing this?

**Comment by illicitonion** [comment]
I'm not sure, sorry! Hopefully if you can fetch some logs from the timing out tests there's something useful in there...

**Comment by UebelAndre** [comment]
I figured out the issue and am now waiting for https://github.com/bazelbuild/bazel/pull/18634

**Comment by UebelAndre** [comment]
@illicitonion or @krasimirgg friendly ping 😅

**Comment by krasimirgg** [comment]
@UebelAndre I'm looking into this, also reading up and going over the dependencies.
From reading https://github.com/bazelbuild/rules_rust/pull/2000#issue-1748346894, I gather this is necessary to support experimental_split_coverage_postprocessing, but from reading
https://github.com/bazelbuild/bazel/pull/18634#issuecomment-1587372808, I gather that this isn't necessary?

So is this just a "nice simplification" towards experimental_split_coverage_postprocessing support?

**Comment by UebelAndre** [comment]
> @UebelAndre I'm looking into this, also reading up and going over the dependencies. From reading [#2000 (comment)](https://github.com/bazelbuild/rules_rust/pull/2000#issue-1748346894), I gather this is necessary to support experimental_split_coverage_postprocessing, but from reading [bazelbuild/bazel#18634 (comment)](https://github.com/bazelbuild/bazel/pull/18634#issuecomment-1587372808), I gather that this isn't necessary?
> 
> So is this just a "nice simplification" towards experimental_split_coverage_postprocessing support?

It turned out it was necessary. If you look athttps://github.com/bazelbuild/bazel/blob/6.3.0/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L204 the fix is using internal functionality from [cc_common](https://bazel.build/versions/6.3.0/rules/lib/cc_common) to add additional files to the coverage action. My assumption was that whatever `rules_cc` did to fix this issue would be usable by `rules_rust` but once I had time to get back to this problem I found that to be false. So, it's a great coincidence that `coverage_common.instrumented_files_info.metadata_files` was made public so pure starlark rules can access the test binary in coverage actions. If there's a better way to implement this though I'm happy to change directions. I only care that coverage works with this flag.

**Comment by krasimirgg** [comment]
Thanks for clarifying! Looks good!

**Review by krasimirgg — APPROVED** [review]

**Pull request merged**
