### PR TITLE
Fix remote build

### PR DESCRIPTION
**Pull request by damienmg**
Tested with local docker build

This was broken by #90. @acmcarther @nlopezgi

### CODE REVIEW

**Comment by mfarrugi** [comment]
@damienmg @buchgr is is possible to check this in the CI now or will it be in the near future?

**Comment by nlopezgi** [comment]
thanks for sending this fix, I will test it with remote execution once its in and let you know if I run into issues.

**Comment by nlopezgi** [comment]
Tested successfully with remote execution. afaik, it should be now possible to setup CI to test your rules with remote execution. I will sync up with @buchgr to provide more info.

**Comment by xingao267** [comment]
I added the config to test rules_rust on RBE in https://github.com/bazelbuild/rules_rust/pull/111, but it seems there are a lot of tests failing on RBE due to some commits between this one and 1944c8a9c104fb73e3058a86204373df63b79eca.

**Pull request merged**
