### PR TITLE
Allow for unnamed workspaces/modules when using crates_vendor

### PR DESCRIPTION
**Pull request by AmeliasCode**
Addresses https://github.com/bazelbuild/rules_rust/issues/2661

If the workspace name is empty, the crate_module_template will use a label like `Label(//<stuff>)` instead of `Label(@//<stuff>)`

Most of the changes in this are just regenerating the vendor'ed crates in the examples. I ran the tests in all the relevant examples to ensure they still worked.

### CODE REVIEW

**Comment by AmeliasCode** [comment]
Seems like the ios failure is unrelated to the change? Is it possible to rerun that test and see?

**Comment by AmeliasCode** [comment]
@illicitonion Hi! Could you take a look at the failure in the CI run and let me know if that looks like an issue with my change? It looks like the tests passed but uploading to Kite failed? 

Thanks!

**Comment by AmeliasCode** [comment]
Looks like everything is passing now! :)

**Comment by AmeliasCode** [comment]
@illicitonion or @UebelAndre could one of you please take a look at this PR? Thanks!!

**Comment by jondo2010** [comment]
I was also just bitten by this issue, trying to use https://github.com/dtolnay/cxx from my project. Can confirm, this PR fixes the underlying issue (but still need to update the vendored build files in `cxx`).

**Comment by AmeliasCode** [comment]
@illicitonion or @UebelAndre Just a friendly ping! Let me know if there is someone else I should message about this! Thanks!!

**Pull request merged**
