### PR TITLE
Add version_file common attr

### PR DESCRIPTION
**Pull request by illicitonion**
This allows folks to generate version files, e.g. using
volatile-status.txt, rather than requiring them to be hard-coded in
BUILD files.

Both ways are still supported, but only one can be used for any
particular target.

I don't love that this moves the version logic into process-wrapper, but the alternatives:
* Need the user to know the 5 different env vars to set in their version_file file
* Write a standalone tool to convert a version_file into a file with the 5 env vars
both seemed worse.

### CODE REVIEW

**Comment by dfreese** [comment]
Implementation LGTM.  Did you have a use case in mind?  Supporting structopt/clap or similar?  The mix of cargo and bazel seems a little odd, but I remember those crates trying to "just work."

Mostly I'm apprehensive about further expanding the API to accommodate cargo, particularly if it means pulling the bazel side of rules rust further away from, "just calling rustc."

**Comment by UebelAndre** [comment]
Any updates here? Is this still a desired change?

**Comment by illicitonion** [comment]
Sorry for the huge delay here!

> Implementation LGTM. Did you have a use case in mind? Supporting structopt/clap or similar? The mix of cargo and bazel seems a little odd, but I remember those crates trying to "just work."

Yeah, we have a bunch of code which uses libraries which auto-detect versions, and this allows them to get their version numbers from the workspace status command when running with `--stamp`, rather than needing version numbers to be hard-coded in BUILD files.

@wchargin also raised a similar request in https://github.com/bazelbuild/rules_rust/issues/553 wanting to consume from a `Cargo.toml` file - a genrule deriving the information and setting this attribute seems like a reasonable piece of machinery for solving that need (which could be hidden away in a macro, if desired).

See also https://github.com/bazelbuild/rules_rust/pull/556 which I've just raised, which adds a more general mechanism for this, because build scripts can't get workspace status command information from `--stamp` because it's in the wrong configuration to see the data. I think this PR is still worth merging regardless, though, because it avoids the user needing to know the 5 env vars they should be setting.

**Comment by UebelAndre** [comment]
I had need for something like this but found there to be a bit more complications around being able to use volatile workspace status info. So I created https://github.com/bazelbuild/rules_rust/pull/956 which I hope might more-or-less solve for similar issues here.

**Comment by UebelAndre** [comment]
> I had need for something like this but found there to be a bit more complications around being able to use volatile workspace status info. So I created #956 which I hope might more-or-less solve for similar issues here. That said though, it clearly wouldn't solve for usability concerns this PR might be solving.

Actually, this PR is quite nice in how it handles version info. Though, I wonder if anyone else has a need for additional volatile status info. Very torn on what the best path forward is

**Comment by UebelAndre** [comment]
Is this something folks are still working-on/interested-in?

**Comment by illicitonion** [comment]
I don't have a particular need, but can push this forwards if anyone else does - how about you @UebelAndre?

**Comment by UebelAndre** [comment]
> I don't have a particular need, but can push this forwards if anyone else does - how about you @UebelAndre?

I noticed that version info was not correctly being propagated into `rust_doc` rules and will (probably at some point) be looking for a way to do so. Since this would impact similar code paths I wanted to find a conclusion to this PR.

**Comment by illicitonion** [comment]
I'll close, but feel free to revive it, or ask me to, if it'd be useful :)

**Pull request closed without merging**
