### PR TITLE
Fix some unit tests to run from another workspace

### PR DESCRIPTION
**Pull request by siddharthab**
Some tests assume that they are running in the rules_rust workspace.
Removing these assumptions allow us to run these tests from other bazel
workspaces.

For example, I help maintain https://github.com/grailbio/bazel-toolchain
and we check if cc toolchain that we configure is compatible with
rules_rust by running the unit tests in this repo.

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]
This looks good to me but I'm not sure if we have a way to regression test something like this so new tests might be added that regress this functionality. Do you know how other rules handle this?

**Comment by siddharthab** [comment]
I don't think it's important to regression test this. I submitted similar changes to rules_go as well. If you do want to regression test it, you can run your test script from a different (dummy) workspace in your git repo.

**Comment by siddharthab** [comment]
Note that the dummy workspace for the regression test won't really be dummy because it will still need to define all the test transitive dependencies (at least until bazel modules are more common).

But I really think it's ok to not have regression tests; it's not common for users to run tests of their dependencies from their own workspace. For the few who do, they can submit fixes as and when these things break.

**Review by illicitonion — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
