### PR TITLE
Prefix `self` for proto imports

### PR DESCRIPTION
**Pull request by jun-sheaf**
This PR prefixes proto imports with `self`. This eliminates ambiguity of imports.

### CODE REVIEW

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Thanks for the pull-request! Is there some kind of regression test you could add for this?

**Comment by jun-sheaf** [comment]
This only matters when using the generated files with cargo, not Bazel.

**Comment by UebelAndre** [comment]
> This only matters when using the generated files with cargo, not Bazel.

What is the error you see? It still feels like something worth having a regression test for if possible.

**Comment by jun-sheaf** [comment]
The 'use' is ambiguous if there is a protobuf file named x containing a message also called x with an enum nested. Since nested enums are namespaced by the message name, 'use x::*' could reference either the enum namespace or the module. the way to fix this is 'self'.

I don't have capacity to build a test.

**Pull request closed without merging**
