### PR TITLE
Release 0.27.0

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Comment by UebelAndre** [comment]
I would like this release to include the following changes
- https://github.com/bazelbuild/rules_rust/pull/2127
- https://github.com/bazelbuild/rules_rust/pull/2124

**Comment by dtolnay** [comment]
I'll add that unit test ASAP today.

**Comment by UebelAndre** [comment]
> I'll add that unit test ASAP today.

Thanks! No rush, just communicating what I'm hoping to have in before merging this PR 😄

**Comment by granaghan** [comment]
It would be great if this release could pick up [this PR](https://github.com/bazelbuild/rules_rust/pull/2123) as well. It's approved and just hitting the same infra failure this release is hitting.

**Comment by dtolnay** [comment]
For the *"_coverage_report.dat: No such file or directory"* failure: I found if you amend and force-push the PR to retrigger the job, eventually it will pass after a few tries.

**Pull request merged**
