### PR TITLE
Update wasm-bindgen to 0.2.89

### PR DESCRIPTION
**Pull request by alexkirsz**
0.2.88 was yanked.

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]
Looks good to me! 

Can you update docs by running `./docs/update-docs.sh`?

**Comment by alexkirsz** [comment]
@UebelAndre Done.

**Comment by alexkirsz** [comment]
@UebelAndre Looks like the instructions in wasm_bindgen/DEVELOPMENT.md are out of date. Not sure how to best update the MODULE.bazel file.

**Comment by UebelAndre** [comment]
@matts1  would you know?

**Comment by matts1** [comment]
See https://buildkite.com/bazel/rules-rust-rustlang/builds/10157#018c8d25-1acb-437b-bf4e-526c0647dfdd/246-271

**Comment by alexkirsz** [comment]
@UebelAndre I ran the following command as prompted to by the CI build command:

```


buildozer 'use_repo_add @rules_rust//rust/private:extensions.bzl internal_deps rules_rust_wasm_bindgen__walrus-0.20.3 rules_rust_wasm_bindgen__wasm-bindgen-0.2.89 rules_rust_wasm_bindgen__wasm-bindgen-cli-support-0.2.89 rules_rust_wasm_bindgen__wasm-bindgen-shared-0.2.89' 'use_repo_remove @rules_rust//rust/private:extensions.bzl internal_deps rules_rust_wasm_bindgen__walrus-0.19.0 rules_rust_wasm_bindgen__wasm-bindgen-0.2.88 rules_rust_wasm_bindgen__wasm-bindgen-cli-support-0.2.88 rules_rust_wasm_bindgen__wasm-bindgen-shared-0.2.88' //MODULE.bazel:all
```

CI is now green :)

**Pull request merged**
