### PR TITLE
Release 0.42.1

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Review by scentini — APPROVED** [review]

**Comment by UebelAndre** [comment]
@scentini @illicitonion i’m not sure of the bzlmod CI issue is fixed but made this release to pull that in. Feel free to merge if you feel the earlier changes fixed the issue. It looked like it would but I haven’t verified myself.

**Review by illicitonion — CHANGES_REQUESTED** [review]
I'm testing, and it's currently broken - will update shortly...

**Comment by illicitonion** [comment]
https://github.com/bazelbuild/rules_rust/pull/2613 fixes this and adds tests :)

**Comment by cameron-martin** [comment]
>I'm testing, and it's currently broken

That's weird, I tested the bzlmod examples with Bazel 6.3 after making the change in #2612, and they seemed to run fine.

**Review by illicitonion — APPROVED** [review]

**Pull request merged**
