### PR TITLE
Pull/expose rustfmt binaries

### PR DESCRIPTION
**Pull request by colatkinson**
See #87.

* Uses `load_arbitrary_tool()` to download `rustfmt` from its independent package (so no need to pull in the full `rust` archive).
  - Can be invoked via `bazel run @rust_linux_x86_64//:rustfmt -- --check $PWD/greeter.rs`.
  - **TODO**: Is there a way to expose this via a platform-independent workspace?
* Retrieves the `rustfmt` hashes in `fetch_shas.sh`.
  - This is currently pretty ugly due to `rustfmt` and `rustc` being independently versioned.
* Sets `LC_ALL=C` in `fetch_shas.sh`.
  - This was actually causing a different sort order for the hashes on my machine. Probably my fault for not correctly configuring my locales. IMO seems like a quick way to avoid pain for other contributors. Can easily be cherry-picked off, though.

Prebuilt binaries don't seem to be available for FreeBSD, so unfortunately the tool won't be available on that platform.

**TODO**: What's the easiest way to write tests for this?
**TODO**: Can the changes to `fetch_shas.sh` be made nicer?

### CODE REVIEW

**Comment by colatkinson** [comment]
@googlebot I signed it!

**Comment by mfarrugi** [comment]
> TODO: Is there a way to expose this via a platform-independent workspace?

I know [`@bazel_tools//tools/cpp:current_cc_toolchain`](https://source.bazel.build/bazel/+/1d205e14e4c069e9199ab71b127c6a6e26a9443b:tools/cpp/BUILD;l=52) exists, but it looks like the aliasing/magic is implemented in Java.

> TODO: What's the easiest way to write tests for this?

You could add a formatting step to one of the codegen rules (ie. protobuf), or write a genrule that invokes rustfmt.

It probably makes sense to make rustfmt available on `rust_toolchain` as part of this so that bindgen, protobuf and any future codegen could make use of it programmatically as well. I think this also simplifies usage from genrules, but not as sure on that.

**Comment by colatkinson** [comment]
Couple of changes:

* `rustfmt` binary is now exposed via the Rust toolchain.
* As suggested, the bindgen rules now fall back on the provided `rustfmt` if available. Tested locally, and it appears to work as intended.
* There's also an explicit test for the binary. A sample rule generates a formatted file from an unformatted one, and `diff` is used to verify that the files differ. Not very comprehensive, so any suggestions on how to beef it up are appreciated.
  - I believe this will fail on BSD, but I haven't yet set up a test environment yet. I haven't been able to determine what the current recommendation is for disabling tests on a platform-specific basis.

**Comment by kornholi** [comment]
Awesome! Is there anything left to do here?

**Comment by mfarrugi** [comment]
lgtm, just need to resolve conflicts.

(sorry for losing track of this, not sure what happened)

**Comment by colatkinson** [comment]
Hey all, I've fixed the conflicts and brought the branch up to date with master. Let me know if there's anything else to do!

**Pull request merged**
