### PR TITLE
Updated `rules_rust` version to `0.6.0`.

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Comment by UebelAndre** [comment]
If possible I'd like this to include:
- https://github.com/bazelbuild/rules_rust/pull/1381
- https://github.com/bazelbuild/rules_rust/pull/1375

**Comment by scentini** [comment]
Could we please also wait for a solution for https://github.com/bazelbuild/rules_rust/issues/1374, which should come today/early next week?

**Comment by kalcutter** [comment]
Please also include #1371 if its possible to get that merged in a reasonable amount of time.

**Comment by kalcutter** [comment]
#1371 has been merged :tada:

**Comment by UebelAndre** [comment]
> Could we please also wait for a solution for #1374, which should come today/early next week?

@scentini hey, any updates here? I'd love to be able to get a release out and think it'd be worth while to do a patch release whenever this is fixed.

**Comment by scentini** [comment]
If a patch release is on the table let's not block 0.6.0. I tried multiple approaches yesterday, but there are some issues with macos behavior (and I haven't gotten yet to checking Windows), and while I'm actively investigating, I don't have a timeline for the fix just yet.

**Comment by UebelAndre** [comment]
> If a patch release is on the table let's not block 0.6.0. I tried multiple approaches yesterday, but there are some issues with macos behavior (and I haven't gotten yet to checking Windows), and while I'm actively investigating, I don't have a timeline for the fix just yet.

I'd like releases to be an easy and light weight thing to do. So I would consider a patch release (or even a new release) something always on the table. Anyone can open a PR updating the version and the automated deploy action takes care of the rest.

**Pull request merged**
