### PR TITLE
Ran Buildifier

### PR DESCRIPTION
**Pull request by UebelAndre**

### CODE REVIEW

**Review by mfarrugi — APPROVED** [review]

**Comment by UebelAndre** [comment]
@mfarrugi Sorry, I meant to open this as a draft. I need to fix up a few things. But this should reduce the amount of changes in #420

**Comment by UebelAndre** [comment]
@mfarrugi Running buildifier in CI will actually require a sizable amount of work. There's many defects in these rules. I think this PR should be merged and a slightly more focused effort should be put on addressing the existing defects.

**Comment by UebelAndre** [comment]
Outstanding defects
```comand
rules_rust % buildifier -lint=warn -mode=check -r ./*
```
```output
./AUTHORS:9:11: syntax error near Inc
./CONTRIBUTING.md:1:8: syntax error near to
./CONTRIBUTORS:12:14: syntax error near Martin
./LICENSE.txt:2:34: syntax error near indent
./README.md:3:2: syntax error near *
./AUTHORS # reformat
./CONTRIBUTING.md # reformat
./CONTRIBUTORS # reformat
./LICENSE.txt # reformat
./README.md # reformat
bindgen/bindgen.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
bindgen/raze/crates.bzl:18: function-docstring: The function "raze_fetch_remote_crates" has no docstring.
A docstring is a string literal (not a comment) which should be the first statement of a function body (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
bindgen/repositories.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
bindgen/repositories.bzl:22: unnamed-macro: The macro "rust_bindgen_repositories" should have a keyword argument called "name".

It is considered a macro because it calls a rule or another macro "native.register_toolchains" on line 47.

By convention, every public macro needs a "name" argument (even if it doesn't use it).
This is important for tooling and automation.

  * If this function is a helper function that's not supposed to be used outside of this file,
    please make it private (e.g. rename it to "_rust_bindgen_repositories").
  * Otherwise, add a "name" argument. If possible, use that name when calling other macros/rules. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unnamed-macro)
cargo/cargo_build_script.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
docs/all.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
docs/rules_proto_stub/proto/defs.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
docs/rules_proto_stub/proto/defs.bzl:1: provider-params: Calls to 'provider' should provide a list of fields and a documentation:\n  provider("description", fields = [...]) (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#provider-params)
proto/proto.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
proto/proto.bzl:17: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
proto/proto.bzl:47: provider-params: Calls to 'provider' should provide a documentation:\n  provider("description", fields = [...]) (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#provider-params)
proto/raze/crates.bzl:18: function-docstring: The function "raze_fetch_remote_crates" has no docstring.
A docstring is a string literal (not a comment) which should be the first statement of a function body (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
proto/repositories.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
proto/toolchain.bzl:30: function-docstring-args: Argument "imports" is not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
proto/toolchain.bzl:30: function-docstring-return: Return value of "rust_generate_proto" is not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-return)
proto/toolchain.bzl:114: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
proto/toolchain.bzl:121: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/known_shas.bzl:2: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/clippy.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/dummy_cc_toolchain/dummy_cc_toolchain.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/legacy_cc_starlark_api_shim.bzl:6: function-docstring-header: The docstring for the function "get_libs_for_static_executable" should start with a one-line summary. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-header)
rust/private/rust.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/rust.bzl:64: function-docstring-args: Arguments "attr", "srcs", "file_name" are not documented.

If the documentation for the arguments exists but is not recognized by Buildifier
make sure it follows the line "Args:" which has the same indentation as the opening """,
and the argument description starts with "<argument_name>:" and indented with at least
one (preferably two) space more than "Args:", for example:

    def crate_root_src(attr):
        """Function description.

        Args:
          attr: argument description, can be
            multiline with additional indentation.
        """ (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
rust/private/rust.bzl:64: function-docstring-return: Return value of "crate_root_src" is not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-return)
rust/private/rust.bzl:158: function-docstring-args: Arguments "toolchain", "output" are not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
rust/private/rust.bzl:163: function-docstring-args: Argument "test_binary" is documented but doesn't exist in the function signature. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
rust/private/rust.bzl:262: rule-impl-return: Avoid using the legacy provider syntax. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#rule-impl-return)
rust/private/rustc.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/rustc.bzl:28: provider-params: Calls to 'provider' should provide a documentation:\n  provider("description", fields = [...]) (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#provider-params)
rust/private/rustc.bzl:44: provider-params: Calls to 'provider' should provide a documentation:\n  provider("description", fields = [...]) (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#provider-params)
rust/private/rustc.bzl:62: provider-params: Calls to 'provider' should provide a documentation:\n  provider("description", fields = [...]) (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#provider-params)
rust/private/rustc.bzl:103: function-docstring-args: Arguments "aliases", "toolchain" are not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
rust/private/rustc.bzl:153: overly-nested-depset: Depset "transitive_crates" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:154: overly-nested-depset: Depset "transitive_crates" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:155: overly-nested-depset: Depset "transitive_dylibs" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:156: overly-nested-depset: Depset "transitive_staticlibs" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:157: overly-nested-depset: Depset "transitive_build_infos" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:165: overly-nested-depset: Depset "transitive_dylibs" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:166: overly-nested-depset: Depset "transitive_staticlibs" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:171: overly-nested-depset: Depset "transitive_build_infos" is potentially overly nested. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset)
rust/private/rustc.bzl:217: function-docstring: The function "get_linker_and_args" has no docstring.
A docstring is a string literal (not a comment) which should be the first statement of a function body (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
rust/private/rustc.bzl:255: function-docstring: The function "collect_inputs" has no docstring.
A docstring is a string literal (not a comment) which should be the first statement of a function body (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
rust/private/rustc.bzl:287: function-docstring: The function "construct_arguments" has no docstring.
A docstring is a string literal (not a comment) which should be the first statement of a function body (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
rust/private/rustc.bzl:428: function-docstring-args: Arguments "ctx", "toolchain", "crate_info", "output_hash", "rust_flags" are not documented.

If the documentation for the arguments exists but is not recognized by Buildifier
make sure it follows the line "Args:" which has the same indentation as the opening """,
and the argument description starts with "<argument_name>:" and indented with at least
one (preferably two) space more than "Args:", for example:

    def rustc_compile_action(ctx):
        """Function description.

        Args:
          ctx: argument description, can be
            multiline with additional indentation.
        """ (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
rust/private/rustc.bzl:515: function-docstring-args: Arguments "ctx", "crate_info", "toolchain", "cc_toolchain", "feature_configuration" are not documented.

If the documentation for the arguments exists but is not recognized by Buildifier
make sure it follows the line "Args:" which has the same indentation as the opening """,
and the argument description starts with "<argument_name>:" and indented with at least
one (preferably two) space more than "Args:", for example:

    def establish_cc_info(ctx):
        """Function description.

        Args:
          ctx: argument description, can be
            multiline with additional indentation.
        """ (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-args)
rust/private/rustc.bzl:515: function-docstring-return: Return value of "establish_cc_info" is not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-return)
rust/private/rustc.bzl:582: function-docstring-header: The docstring for the function "_compute_rpaths" should start with a one-line summary. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-header)
rust/private/rustdoc.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/rustdoc.bzl:112: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/private/rustdoc_test.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/private/rustdoc_test.bzl:54: rule-impl-return: Avoid using the legacy provider syntax. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#rule-impl-return)
rust/private/transitions.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/repositories.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/repositories.bzl:8: unnamed-macro: The macro "rust_repositories" should have a keyword argument called "name".

It is considered a macro because it calls a rule or another macro "rust_repository_set" on line 96.

By convention, every public macro needs a "name" argument (even if it doesn't use it).
This is important for tooling and automation.

  * If this function is a helper function that's not supposed to be used outside of this file,
    please make it private (e.g. rename it to "_rust_repositories").
  * Otherwise, add a "name" argument. If possible, use that name when calling other macros/rules. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unnamed-macro)
rust/rust.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
rust/rust.bzl:38: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:41: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:44: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:47: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:50: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:53: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:56: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:59: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
rust/rust.bzl:62: no-effect: Expression result is not used. Docstrings should be the first statements of a file or a function (they may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
test/rustfmt/rustfmt_generator.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
wasm_bindgen/raze/crates.bzl:18: function-docstring: The function "raze_fetch_remote_crates" has no docstring.
A docstring is a string literal (not a comment) which should be the first statement of a function body (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
wasm_bindgen/repositories.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
wasm_bindgen/repositories.bzl:22: unnamed-macro: The macro "rust_wasm_bindgen_repositories" should have a keyword argument called "name".

It is considered a macro because it calls a rule or another macro "native.register_toolchains" on line 36.

By convention, every public macro needs a "name" argument (even if it doesn't use it).
This is important for tooling and automation.

  * If this function is a helper function that's not supposed to be used outside of this file,
    please make it private (e.g. rename it to "_rust_wasm_bindgen_repositories").
  * Otherwise, add a "name" argument. If possible, use that name when calling other macros/rules. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unnamed-macro)
wasm_bindgen/wasm_bindgen.bzl:15: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
wasm_bindgen/wasm_bindgen.bzl:43: rule-impl-return: Avoid using the legacy provider syntax. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#rule-impl-return)
./workspace.bzl:1: module-docstring: The file has no module docstring.
A module docstring is a string literal (not a comment) which should be the first statement of a file (it may follow comment lines). (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#module-docstring)
```

**Comment by UebelAndre** [comment]
#420 addresses some of this with the updated documentation.

**Comment by UebelAndre** [comment]
@mfarrugi ready for another review

**Pull request merged**
