### PR TITLE
Update rust to 1.33.0

### PR DESCRIPTION
**Pull request by cbranch**

### CODE REVIEW

**Comment by mjduijn** [comment]
Ping (would very much like to move to 1.33)

If it helps I can create a new PR with the changes

**Comment by damienmg** [comment]
mjduijn@: you can create a new PR as long as you don't copy this one. We can only accept this one if the original author @cbranch sign the Google CLA.

**Comment by mjduijn** [comment]
@damienmg done in #210

**Comment by damienmg** [comment]
Thanks @mjduijn !

**Pull request closed without merging**
