### PR TITLE
Fixed genquery for rust targets

### PR DESCRIPTION
**Pull request by UebelAndre**
relates to https://github.com/bazelbuild/rules_rust/issues/2522

### CODE REVIEW

**Review by daivinhtran — COMMENTED** [review]
I'm not an expert in this corner of the rules but shouldn't we also remove [this](https://github.com/bazelbuild/rules_rust/blob/8b977b5f7020fc3a3b3bbc318e414269014f126a/rust/private/utils.bzl#L486) altogether?

**Comment by UebelAndre** [comment]
> I'm not an expert in this corner of the rules but shouldn't we also remove [this](https://github.com/bazelbuild/rules_rust/blob/8b977b5f7020fc3a3b3bbc318e414269014f126a/rust/private/utils.bzl#L486) altogether?

I'm not sure this should be completely deleted to follow the spirit of https://github.com/bazelbuild/rules_rust/issues/2383#issuecomment-1883287133. Sounds like Google has a use for this code but I don't think it's acceptable to have basic functionality be broken by a shell of a tool. If there is a more desired outcome then I'm happy to update the PR if the change is small. But I think it should fall to Googlers to improve `//util/import` to the point where it can coexist with the rest of rules_rust.

**Comment by daivinhtran** [comment]
@UebelAndre 

Would you mind waiting until @scentini is back next week? @scentini has more context and is on vacation this week. I need to sync with them to have a better understanding.

**Comment by scentini** [comment]
Thanks folks! We indeed still use the import macro in google's internal codebase and the PR in its current form works the best;
I will do some investigation on what is expected from genquery in this context.

**Review by scentini — APPROVED** [review]

**Pull request merged**
