### PR TITLE
crate_universe: Don't preform path translation on `out_dir`

### PR DESCRIPTION
**Pull request by konkers**
Bug: #2801

### CODE REVIEW

**Comment by krasimirgg** [comment]
Thank you! Could you also set up a new presubmit running some of the blzmod examples with `--incompatible_use_plus_in_repo_names`.

**Comment by konkers** [comment]
Apologies for the noise.  Trying to get CI working.

**Comment by konkers** [comment]
OK churn done.  I have added tests using `--incompatible_use_plus_in_repo_names`.   This was a bit complicated by the fact that

1. The command line flag does not exist in the bazel version use by the test by default
2. The repo names leak into the lock file causing `--lockfile_mode=error` to fail

**Review by krasimirgg — APPROVED** [review]
Thank you!

**Pull request merged**
