### PR TITLE
Allow multiple uses of extra_rustc_flags

### PR DESCRIPTION
**Pull request by mypmc**
I would like to support the following use cases.

In `.bazelrc`.
```
build:dev --@rules_rust//:extra_rustc_flags="-C..."
build:test --config=dev
build:test --@rules_rust//:extra_rustc_flags="-C..." # add additional flags
build:fuzz --config=test
build:fuzz --@rules_rust//:extra_rustc_flags="-Cpasses=sancov,-Cllvm-args=-sanitizer-coverage-level=3,-Cllvm-args=-sanitizer-coverage-inline-8bit-counters,-Znew-llvm-pass-manager=no"
```

### CODE REVIEW

**Comment by mypmc** [comment]
[out of luck](https://github.com/bazelbuild/bazel/issues/13064#issuecomment-782548200) :(

> Bazel 4.0.0's baseline was cut on Nov 18. The `allow_multiple` parameter to `config.string()` was added on Dec 10. You can use a version of Bazel closer to head if you want to experiment with this feature.

**Comment by mypmc** [comment]
> Whenever there is a new [Bazel LTS release](https://blog.bazel.build/2020/11/10/long-term-support-release.html), all releases of `rules_rust` will maintain support for the older LTS version for at least 3 months unless Bazel doesn't allow this.

Bumped the min bazel version but I have no idea this met the `rules_rust` policy.

**Comment by hlopko** [comment]
Could you move the min supported bazel version bump to a separate PR please? It's a big-ish deal so it's good to not have it hidden in this PR.

**Comment by hlopko** [comment]
Otherwise looks good to me, but I'll kindly ask @krasimirgg to double check.

**Comment by UebelAndre** [comment]
Perhaps this should be an upstream issue for Bazel to allow multiple string_list flags?

**Comment by mypmc** [comment]
related??
- https://github.com/bazelbuild/proposals/pull/248
- https://github.com/bazelbuild/bazel/pull/14911

---

I have an another idea. How about introducing new build setting e.g., `extra_rustc_flag`?

```
build --@rules_rust//:extra_rustc_flags="-C...,-C...,-Z..."

build:dev --@rules_rust//:extra_rustc_flag="-C..."
build:dev --@rules_rust//:extra_rustc_flag="-C..."

build:test --config=dev
build:test --@rules_rust//:extra_rustc_flag="-C..."

build:fuzz --config=test
build:fuzz --@rules_rust//:extra_rustc_flag="-C..."
build:fuzz --@rules_rust//:extra_rustc_flag="-C..."
build:fuzz --@rules_rust//:extra_rustc_flag="-Z..."
```

Looks verbose but straightforward to extend flags. What do you think?

**Comment by krasimirgg** [comment]
>I have an another idea. How about introducing new build setting e.g., extra_rustc_flag?

I like this, to clarify a bit the semantics I read from your proposal: we keep the extra_rustc_flags as-is (string_list), and extra_rustc_flag is string + allow_multiple=true, and each extra_rustc_flag is singular (not split by comma), and the extra_rustc_flag-s are appended after the extra_rustc_flags.

**Comment by mypmc** [comment]
Created #1413, so I will close this PR. Thanks for your review.

**Pull request closed without merging**
