### PR TITLE
Fixed errors with non-absolute labels

### PR DESCRIPTION
**Pull request by UebelAndre**
This fixes the following errors when building post https://github.com/bazelbuild/rules_rust/pull/1159
```
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/c4900dc498759a5aae30fdfe5c69c114/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//docs:cargo_bazel_rustdoc' failed; build aborted: no such package 'rust/settings': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/user/Code/cargo-bazel/rust/settings
```

### CODE REVIEW

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/pull/1159#issuecomment-1065434355
> Bisected to this commit, when trying to upgrade rules_rust. This triggered the following error for me:
> 
> ```
>     //proto/protobuf:protobuf_prost_generated (782077f4a782b271e6081e5d253d233307fbb065ebd24cbeda52275882be7e2c)
>     //tools/prostgen:prostgen (ad7becf1f627c98f4c44ac49f5991ab41aa98662628ab4c26b029d7fb1035392)
> .-> @rules_rust//util/process_wrapper:process_wrapper (ad7becf1f627c98f4c44ac49f5991ab41aa98662628ab4c26b029d7fb1035392)
> |   @rules_rust//util/process_wrapper:process_wrapper_impl (ad7becf1f627c98f4c44ac49f5991ab41aa98662628ab4c26b029d7fb1035392)
> |   @rules_rust//util/process_wrapper:process_wrapper_bin (ad7becf1f627c98f4c44ac49f5991ab41aa98662628ab4c26b029d7fb1035392)
> `-- @rules_rust//util/process_wrapper:process_wrapper (ad7becf1f627c98f4c44ac49f5991ab41aa98662628ab4c26b029d7fb1035392)
> ```
> 
> Where the protobuf:protobuf_prost_generated target depends on the prostgen tool. This was in the `host` configuration. If I switched that to the `exec` configuration, the error went away, but it does seem like there's potentially a problem for rules that expected to be run on `host`.

This is also impacting this PR.

**Review by dfreese — APPROVED** [review]

**Comment by UebelAndre** [comment]
@dfreese  do you have a solution to the error in https://github.com/bazelbuild/rules_rust/pull/1185#issuecomment-1065438326 ?

**Comment by dfreese** [comment]
> @dfreese do you have a solution to the error in [#1185 (comment)](https://github.com/bazelbuild/rules_rust/pull/1185#issuecomment-1065438326) ?

nothing concrete beyond what I mentioned in that initial comment, which I don't think directly translates.  I'm trying to work on a minimally reproducible test case, but was running into the issue this PR addresses.

**Comment by dfreese** [comment]
I put together this https://github.com/bazelbuild/rules_rust/pull/1187, which fixes both problems, I think.

**Comment by UebelAndre** [comment]
This change was addressed by https://github.com/bazelbuild/rules_rust/pull/1187

**Pull request closed without merging**
